server:
  port: 18080

quartz:
  enabled: true

xdaili:
  secret: ZF20179259363xxYvyk
  order: 6e3d4d41727f454d983a7ef7fa206e5d
  url: forward.xdaili.cn
  port: 80
proxy:
  custome: http://116.196.86.186:35050/api/v1/proxy/?https=1
  jhao104 :
    get : http://192.168.1.26:5010/get/
    delete : http://192.168.1.26:5010/delete/
spring:
  aop:
    proxy-target-class: true
  jpa:
    open-in-view: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: 0.0.0.0/8
