rule "bath_rule_178__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_178__0 " + $d);
end

rule "bath_rule_178__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_178__1 " + $d);
end

rule "bath_rule_178__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_178__2 " + $d);
end

rule "bath_rule_178__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_178__3 " + $d);
end

rule "bath_rule_178__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_178__4 " + $d);
end

rule "bath_rule_178__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_178__5 " + $d);
end

rule "bath_rule_178__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_178__6 " + $d);
end

rule "bath_rule_178__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_178__7 " + $d);
end

rule "bath_rule_178__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_178__8 " + $d);
end

rule "bath_rule_178__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_178__9 " + $d);
end

rule "bath_rule_178__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_178__10 " + $d);
end

rule "bath_rule_178__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_178__11 " + $d);
end

rule "bath_rule_178__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_178__12 " + $d);
end

rule "bath_rule_178__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_178__13 " + $d);
end

rule "bath_rule_178__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_178__14 " + $d);
end

rule "bath_rule_178__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_178__15 " + $d);
end

rule "bath_rule_178__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_178__16 " + $d);
end

rule "bath_rule_178__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_178__17 " + $d);
end

rule "bath_rule_178__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_178__18 " + $d);
end

rule "bath_rule_178__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_178__19 " + $d);
end

rule "bath_rule_178__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_178__20 " + $d);
end

rule "bath_rule_178__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_178__21 " + $d);
end

rule "bath_rule_178__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_178__22 " + $d);
end

rule "bath_rule_178__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_178__23 " + $d);
end

rule "bath_rule_178__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_178__24 " + $d);
end

rule "bath_rule_178__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_178__25 " + $d);
end

rule "bath_rule_178__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_178__26 " + $d);
end

rule "bath_rule_178__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_178__27 " + $d);
end

rule "bath_rule_178__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_178__28 " + $d);
end

rule "bath_rule_178__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_178__29 " + $d);
end

rule "bath_rule_178__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_178__30 " + $d);
end

rule "bath_rule_178__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_178__31 " + $d);
end

rule "bath_rule_178__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_178__32 " + $d);
end

rule "bath_rule_178__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_178__33 " + $d);
end

rule "bath_rule_178__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_178__34 " + $d);
end

rule "bath_rule_178__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_178__35 " + $d);
end

rule "bath_rule_178__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_178__36 " + $d);
end

rule "bath_rule_178__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_178__37 " + $d);
end

rule "bath_rule_178__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_178__38 " + $d);
end

rule "bath_rule_178__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_178__39 " + $d);
end

rule "bath_rule_178__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_178__40 " + $d);
end

rule "bath_rule_178__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_178__41 " + $d);
end

rule "bath_rule_178__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_178__42 " + $d);
end

rule "bath_rule_178__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_178__43 " + $d);
end

rule "bath_rule_178__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_178__44 " + $d);
end

rule "bath_rule_178__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_178__45 " + $d);
end

rule "bath_rule_178__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_178__46 " + $d);
end

rule "bath_rule_178__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_178__47 " + $d);
end

rule "bath_rule_178__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_178__48 " + $d);
end

rule "bath_rule_178__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_178__49 " + $d);
end

rule "bath_rule_178__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_178__50 " + $d);
end

rule "bath_rule_178__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_178__51 " + $d);
end

rule "bath_rule_178__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_178__52 " + $d);
end

rule "bath_rule_178__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_178__53 " + $d);
end

rule "bath_rule_178__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_178__54 " + $d);
end

rule "bath_rule_178__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_178__55 " + $d);
end

rule "bath_rule_178__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_178__56 " + $d);
end

rule "bath_rule_178__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_178__57 " + $d);
end

rule "bath_rule_178__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_178__58 " + $d);
end

rule "bath_rule_178__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_178__59 " + $d);
end

rule "bath_rule_178__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_178__60 " + $d);
end

rule "bath_rule_178__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_178__61 " + $d);
end

rule "bath_rule_178__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_178__62 " + $d);
end

rule "bath_rule_178__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_178__63 " + $d);
end

rule "bath_rule_178__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_178__64 " + $d);
end

rule "bath_rule_178__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_178__65 " + $d);
end

rule "bath_rule_178__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_178__66 " + $d);
end

rule "bath_rule_178__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_178__67 " + $d);
end

rule "bath_rule_178__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_178__68 " + $d);
end

rule "bath_rule_178__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_178__69 " + $d);
end

rule "bath_rule_178__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_178__70 " + $d);
end

rule "bath_rule_178__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_178__71 " + $d);
end

rule "bath_rule_178__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_178__72 " + $d);
end

rule "bath_rule_178__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_178__73 " + $d);
end

rule "bath_rule_178__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_178__74 " + $d);
end

rule "bath_rule_178__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_178__75 " + $d);
end

rule "bath_rule_178__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_178__76 " + $d);
end

rule "bath_rule_178__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_178__77 " + $d);
end

rule "bath_rule_178__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_178__78 " + $d);
end

rule "bath_rule_178__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_178__79 " + $d);
end

rule "bath_rule_178__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_178__80 " + $d);
end

rule "bath_rule_178__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_178__81 " + $d);
end

rule "bath_rule_178__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_178__82 " + $d);
end

rule "bath_rule_178__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_178__83 " + $d);
end

rule "bath_rule_178__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_178__84 " + $d);
end

rule "bath_rule_178__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_178__85 " + $d);
end

rule "bath_rule_178__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_178__86 " + $d);
end

rule "bath_rule_178__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_178__87 " + $d);
end

rule "bath_rule_178__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_178__88 " + $d);
end

rule "bath_rule_178__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_178__89 " + $d);
end

rule "bath_rule_178__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_178__90 " + $d);
end

rule "bath_rule_178__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_178__91 " + $d);
end

rule "bath_rule_178__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_178__92 " + $d);
end

rule "bath_rule_178__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_178__93 " + $d);
end

rule "bath_rule_178__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_178__94 " + $d);
end

rule "bath_rule_178__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_178__95 " + $d);
end

rule "bath_rule_178__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_178__96 " + $d);
end

rule "bath_rule_178__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_178__97 " + $d);
end

rule "bath_rule_178__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_178__98 " + $d);
end

rule "bath_rule_178__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_178__99 " + $d);
end

rule "bath_rule_178__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_178__100 " + $d);
end

