rule "bath_rule_290__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_290__0 " + $d);
end

rule "bath_rule_290__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_290__1 " + $d);
end

rule "bath_rule_290__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_290__2 " + $d);
end

rule "bath_rule_290__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_290__3 " + $d);
end

rule "bath_rule_290__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_290__4 " + $d);
end

rule "bath_rule_290__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_290__5 " + $d);
end

rule "bath_rule_290__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_290__6 " + $d);
end

rule "bath_rule_290__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_290__7 " + $d);
end

rule "bath_rule_290__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_290__8 " + $d);
end

rule "bath_rule_290__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_290__9 " + $d);
end

rule "bath_rule_290__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_290__10 " + $d);
end

rule "bath_rule_290__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_290__11 " + $d);
end

rule "bath_rule_290__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_290__12 " + $d);
end

rule "bath_rule_290__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_290__13 " + $d);
end

rule "bath_rule_290__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_290__14 " + $d);
end

rule "bath_rule_290__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_290__15 " + $d);
end

rule "bath_rule_290__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_290__16 " + $d);
end

rule "bath_rule_290__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_290__17 " + $d);
end

rule "bath_rule_290__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_290__18 " + $d);
end

rule "bath_rule_290__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_290__19 " + $d);
end

rule "bath_rule_290__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_290__20 " + $d);
end

rule "bath_rule_290__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_290__21 " + $d);
end

rule "bath_rule_290__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_290__22 " + $d);
end

rule "bath_rule_290__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_290__23 " + $d);
end

rule "bath_rule_290__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_290__24 " + $d);
end

rule "bath_rule_290__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_290__25 " + $d);
end

rule "bath_rule_290__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_290__26 " + $d);
end

rule "bath_rule_290__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_290__27 " + $d);
end

rule "bath_rule_290__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_290__28 " + $d);
end

rule "bath_rule_290__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_290__29 " + $d);
end

rule "bath_rule_290__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_290__30 " + $d);
end

rule "bath_rule_290__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_290__31 " + $d);
end

rule "bath_rule_290__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_290__32 " + $d);
end

rule "bath_rule_290__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_290__33 " + $d);
end

rule "bath_rule_290__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_290__34 " + $d);
end

rule "bath_rule_290__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_290__35 " + $d);
end

rule "bath_rule_290__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_290__36 " + $d);
end

rule "bath_rule_290__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_290__37 " + $d);
end

rule "bath_rule_290__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_290__38 " + $d);
end

rule "bath_rule_290__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_290__39 " + $d);
end

rule "bath_rule_290__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_290__40 " + $d);
end

rule "bath_rule_290__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_290__41 " + $d);
end

rule "bath_rule_290__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_290__42 " + $d);
end

rule "bath_rule_290__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_290__43 " + $d);
end

rule "bath_rule_290__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_290__44 " + $d);
end

rule "bath_rule_290__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_290__45 " + $d);
end

rule "bath_rule_290__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_290__46 " + $d);
end

rule "bath_rule_290__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_290__47 " + $d);
end

rule "bath_rule_290__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_290__48 " + $d);
end

rule "bath_rule_290__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_290__49 " + $d);
end

rule "bath_rule_290__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_290__50 " + $d);
end

rule "bath_rule_290__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_290__51 " + $d);
end

rule "bath_rule_290__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_290__52 " + $d);
end

rule "bath_rule_290__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_290__53 " + $d);
end

rule "bath_rule_290__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_290__54 " + $d);
end

rule "bath_rule_290__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_290__55 " + $d);
end

rule "bath_rule_290__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_290__56 " + $d);
end

rule "bath_rule_290__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_290__57 " + $d);
end

rule "bath_rule_290__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_290__58 " + $d);
end

rule "bath_rule_290__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_290__59 " + $d);
end

rule "bath_rule_290__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_290__60 " + $d);
end

rule "bath_rule_290__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_290__61 " + $d);
end

rule "bath_rule_290__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_290__62 " + $d);
end

rule "bath_rule_290__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_290__63 " + $d);
end

rule "bath_rule_290__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_290__64 " + $d);
end

rule "bath_rule_290__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_290__65 " + $d);
end

rule "bath_rule_290__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_290__66 " + $d);
end

rule "bath_rule_290__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_290__67 " + $d);
end

rule "bath_rule_290__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_290__68 " + $d);
end

rule "bath_rule_290__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_290__69 " + $d);
end

rule "bath_rule_290__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_290__70 " + $d);
end

rule "bath_rule_290__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_290__71 " + $d);
end

rule "bath_rule_290__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_290__72 " + $d);
end

rule "bath_rule_290__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_290__73 " + $d);
end

rule "bath_rule_290__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_290__74 " + $d);
end

rule "bath_rule_290__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_290__75 " + $d);
end

rule "bath_rule_290__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_290__76 " + $d);
end

rule "bath_rule_290__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_290__77 " + $d);
end

rule "bath_rule_290__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_290__78 " + $d);
end

rule "bath_rule_290__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_290__79 " + $d);
end

rule "bath_rule_290__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_290__80 " + $d);
end

rule "bath_rule_290__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_290__81 " + $d);
end

rule "bath_rule_290__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_290__82 " + $d);
end

rule "bath_rule_290__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_290__83 " + $d);
end

rule "bath_rule_290__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_290__84 " + $d);
end

rule "bath_rule_290__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_290__85 " + $d);
end

rule "bath_rule_290__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_290__86 " + $d);
end

rule "bath_rule_290__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_290__87 " + $d);
end

rule "bath_rule_290__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_290__88 " + $d);
end

rule "bath_rule_290__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_290__89 " + $d);
end

rule "bath_rule_290__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_290__90 " + $d);
end

rule "bath_rule_290__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_290__91 " + $d);
end

rule "bath_rule_290__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_290__92 " + $d);
end

rule "bath_rule_290__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_290__93 " + $d);
end

rule "bath_rule_290__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_290__94 " + $d);
end

rule "bath_rule_290__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_290__95 " + $d);
end

rule "bath_rule_290__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_290__96 " + $d);
end

rule "bath_rule_290__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_290__97 " + $d);
end

rule "bath_rule_290__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_290__98 " + $d);
end

rule "bath_rule_290__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_290__99 " + $d);
end

rule "bath_rule_290__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_290__100 " + $d);
end

