rule "bath_rule_222__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_222__0 " + $d);
end

rule "bath_rule_222__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_222__1 " + $d);
end

rule "bath_rule_222__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_222__2 " + $d);
end

rule "bath_rule_222__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_222__3 " + $d);
end

rule "bath_rule_222__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_222__4 " + $d);
end

rule "bath_rule_222__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_222__5 " + $d);
end

rule "bath_rule_222__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_222__6 " + $d);
end

rule "bath_rule_222__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_222__7 " + $d);
end

rule "bath_rule_222__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_222__8 " + $d);
end

rule "bath_rule_222__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_222__9 " + $d);
end

rule "bath_rule_222__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_222__10 " + $d);
end

rule "bath_rule_222__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_222__11 " + $d);
end

rule "bath_rule_222__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_222__12 " + $d);
end

rule "bath_rule_222__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_222__13 " + $d);
end

rule "bath_rule_222__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_222__14 " + $d);
end

rule "bath_rule_222__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_222__15 " + $d);
end

rule "bath_rule_222__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_222__16 " + $d);
end

rule "bath_rule_222__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_222__17 " + $d);
end

rule "bath_rule_222__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_222__18 " + $d);
end

rule "bath_rule_222__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_222__19 " + $d);
end

rule "bath_rule_222__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_222__20 " + $d);
end

rule "bath_rule_222__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_222__21 " + $d);
end

rule "bath_rule_222__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_222__22 " + $d);
end

rule "bath_rule_222__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_222__23 " + $d);
end

rule "bath_rule_222__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_222__24 " + $d);
end

rule "bath_rule_222__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_222__25 " + $d);
end

rule "bath_rule_222__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_222__26 " + $d);
end

rule "bath_rule_222__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_222__27 " + $d);
end

rule "bath_rule_222__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_222__28 " + $d);
end

rule "bath_rule_222__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_222__29 " + $d);
end

rule "bath_rule_222__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_222__30 " + $d);
end

rule "bath_rule_222__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_222__31 " + $d);
end

rule "bath_rule_222__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_222__32 " + $d);
end

rule "bath_rule_222__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_222__33 " + $d);
end

rule "bath_rule_222__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_222__34 " + $d);
end

rule "bath_rule_222__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_222__35 " + $d);
end

rule "bath_rule_222__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_222__36 " + $d);
end

rule "bath_rule_222__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_222__37 " + $d);
end

rule "bath_rule_222__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_222__38 " + $d);
end

rule "bath_rule_222__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_222__39 " + $d);
end

rule "bath_rule_222__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_222__40 " + $d);
end

rule "bath_rule_222__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_222__41 " + $d);
end

rule "bath_rule_222__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_222__42 " + $d);
end

rule "bath_rule_222__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_222__43 " + $d);
end

rule "bath_rule_222__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_222__44 " + $d);
end

rule "bath_rule_222__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_222__45 " + $d);
end

rule "bath_rule_222__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_222__46 " + $d);
end

rule "bath_rule_222__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_222__47 " + $d);
end

rule "bath_rule_222__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_222__48 " + $d);
end

rule "bath_rule_222__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_222__49 " + $d);
end

rule "bath_rule_222__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_222__50 " + $d);
end

rule "bath_rule_222__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_222__51 " + $d);
end

rule "bath_rule_222__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_222__52 " + $d);
end

rule "bath_rule_222__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_222__53 " + $d);
end

rule "bath_rule_222__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_222__54 " + $d);
end

rule "bath_rule_222__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_222__55 " + $d);
end

rule "bath_rule_222__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_222__56 " + $d);
end

rule "bath_rule_222__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_222__57 " + $d);
end

rule "bath_rule_222__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_222__58 " + $d);
end

rule "bath_rule_222__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_222__59 " + $d);
end

rule "bath_rule_222__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_222__60 " + $d);
end

rule "bath_rule_222__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_222__61 " + $d);
end

rule "bath_rule_222__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_222__62 " + $d);
end

rule "bath_rule_222__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_222__63 " + $d);
end

rule "bath_rule_222__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_222__64 " + $d);
end

rule "bath_rule_222__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_222__65 " + $d);
end

rule "bath_rule_222__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_222__66 " + $d);
end

rule "bath_rule_222__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_222__67 " + $d);
end

rule "bath_rule_222__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_222__68 " + $d);
end

rule "bath_rule_222__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_222__69 " + $d);
end

rule "bath_rule_222__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_222__70 " + $d);
end

rule "bath_rule_222__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_222__71 " + $d);
end

rule "bath_rule_222__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_222__72 " + $d);
end

rule "bath_rule_222__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_222__73 " + $d);
end

rule "bath_rule_222__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_222__74 " + $d);
end

rule "bath_rule_222__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_222__75 " + $d);
end

rule "bath_rule_222__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_222__76 " + $d);
end

rule "bath_rule_222__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_222__77 " + $d);
end

rule "bath_rule_222__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_222__78 " + $d);
end

rule "bath_rule_222__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_222__79 " + $d);
end

rule "bath_rule_222__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_222__80 " + $d);
end

rule "bath_rule_222__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_222__81 " + $d);
end

rule "bath_rule_222__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_222__82 " + $d);
end

rule "bath_rule_222__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_222__83 " + $d);
end

rule "bath_rule_222__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_222__84 " + $d);
end

rule "bath_rule_222__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_222__85 " + $d);
end

rule "bath_rule_222__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_222__86 " + $d);
end

rule "bath_rule_222__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_222__87 " + $d);
end

rule "bath_rule_222__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_222__88 " + $d);
end

rule "bath_rule_222__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_222__89 " + $d);
end

rule "bath_rule_222__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_222__90 " + $d);
end

rule "bath_rule_222__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_222__91 " + $d);
end

rule "bath_rule_222__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_222__92 " + $d);
end

rule "bath_rule_222__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_222__93 " + $d);
end

rule "bath_rule_222__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_222__94 " + $d);
end

rule "bath_rule_222__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_222__95 " + $d);
end

rule "bath_rule_222__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_222__96 " + $d);
end

rule "bath_rule_222__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_222__97 " + $d);
end

rule "bath_rule_222__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_222__98 " + $d);
end

rule "bath_rule_222__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_222__99 " + $d);
end

rule "bath_rule_222__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_222__100 " + $d);
end

