rule "bath_rule_350__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_350__0 " + $d);
end

rule "bath_rule_350__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_350__1 " + $d);
end

rule "bath_rule_350__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_350__2 " + $d);
end

rule "bath_rule_350__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_350__3 " + $d);
end

rule "bath_rule_350__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_350__4 " + $d);
end

rule "bath_rule_350__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_350__5 " + $d);
end

rule "bath_rule_350__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_350__6 " + $d);
end

rule "bath_rule_350__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_350__7 " + $d);
end

rule "bath_rule_350__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_350__8 " + $d);
end

rule "bath_rule_350__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_350__9 " + $d);
end

rule "bath_rule_350__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_350__10 " + $d);
end

rule "bath_rule_350__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_350__11 " + $d);
end

rule "bath_rule_350__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_350__12 " + $d);
end

rule "bath_rule_350__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_350__13 " + $d);
end

rule "bath_rule_350__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_350__14 " + $d);
end

rule "bath_rule_350__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_350__15 " + $d);
end

rule "bath_rule_350__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_350__16 " + $d);
end

rule "bath_rule_350__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_350__17 " + $d);
end

rule "bath_rule_350__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_350__18 " + $d);
end

rule "bath_rule_350__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_350__19 " + $d);
end

rule "bath_rule_350__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_350__20 " + $d);
end

rule "bath_rule_350__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_350__21 " + $d);
end

rule "bath_rule_350__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_350__22 " + $d);
end

rule "bath_rule_350__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_350__23 " + $d);
end

rule "bath_rule_350__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_350__24 " + $d);
end

rule "bath_rule_350__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_350__25 " + $d);
end

rule "bath_rule_350__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_350__26 " + $d);
end

rule "bath_rule_350__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_350__27 " + $d);
end

rule "bath_rule_350__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_350__28 " + $d);
end

rule "bath_rule_350__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_350__29 " + $d);
end

rule "bath_rule_350__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_350__30 " + $d);
end

rule "bath_rule_350__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_350__31 " + $d);
end

rule "bath_rule_350__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_350__32 " + $d);
end

rule "bath_rule_350__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_350__33 " + $d);
end

rule "bath_rule_350__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_350__34 " + $d);
end

rule "bath_rule_350__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_350__35 " + $d);
end

rule "bath_rule_350__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_350__36 " + $d);
end

rule "bath_rule_350__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_350__37 " + $d);
end

rule "bath_rule_350__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_350__38 " + $d);
end

rule "bath_rule_350__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_350__39 " + $d);
end

rule "bath_rule_350__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_350__40 " + $d);
end

rule "bath_rule_350__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_350__41 " + $d);
end

rule "bath_rule_350__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_350__42 " + $d);
end

rule "bath_rule_350__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_350__43 " + $d);
end

rule "bath_rule_350__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_350__44 " + $d);
end

rule "bath_rule_350__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_350__45 " + $d);
end

rule "bath_rule_350__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_350__46 " + $d);
end

rule "bath_rule_350__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_350__47 " + $d);
end

rule "bath_rule_350__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_350__48 " + $d);
end

rule "bath_rule_350__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_350__49 " + $d);
end

rule "bath_rule_350__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_350__50 " + $d);
end

rule "bath_rule_350__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_350__51 " + $d);
end

rule "bath_rule_350__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_350__52 " + $d);
end

rule "bath_rule_350__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_350__53 " + $d);
end

rule "bath_rule_350__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_350__54 " + $d);
end

rule "bath_rule_350__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_350__55 " + $d);
end

rule "bath_rule_350__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_350__56 " + $d);
end

rule "bath_rule_350__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_350__57 " + $d);
end

rule "bath_rule_350__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_350__58 " + $d);
end

rule "bath_rule_350__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_350__59 " + $d);
end

rule "bath_rule_350__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_350__60 " + $d);
end

rule "bath_rule_350__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_350__61 " + $d);
end

rule "bath_rule_350__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_350__62 " + $d);
end

rule "bath_rule_350__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_350__63 " + $d);
end

rule "bath_rule_350__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_350__64 " + $d);
end

rule "bath_rule_350__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_350__65 " + $d);
end

rule "bath_rule_350__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_350__66 " + $d);
end

rule "bath_rule_350__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_350__67 " + $d);
end

rule "bath_rule_350__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_350__68 " + $d);
end

rule "bath_rule_350__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_350__69 " + $d);
end

rule "bath_rule_350__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_350__70 " + $d);
end

rule "bath_rule_350__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_350__71 " + $d);
end

rule "bath_rule_350__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_350__72 " + $d);
end

rule "bath_rule_350__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_350__73 " + $d);
end

rule "bath_rule_350__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_350__74 " + $d);
end

rule "bath_rule_350__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_350__75 " + $d);
end

rule "bath_rule_350__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_350__76 " + $d);
end

rule "bath_rule_350__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_350__77 " + $d);
end

rule "bath_rule_350__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_350__78 " + $d);
end

rule "bath_rule_350__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_350__79 " + $d);
end

rule "bath_rule_350__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_350__80 " + $d);
end

rule "bath_rule_350__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_350__81 " + $d);
end

rule "bath_rule_350__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_350__82 " + $d);
end

rule "bath_rule_350__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_350__83 " + $d);
end

rule "bath_rule_350__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_350__84 " + $d);
end

rule "bath_rule_350__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_350__85 " + $d);
end

rule "bath_rule_350__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_350__86 " + $d);
end

rule "bath_rule_350__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_350__87 " + $d);
end

rule "bath_rule_350__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_350__88 " + $d);
end

rule "bath_rule_350__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_350__89 " + $d);
end

rule "bath_rule_350__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_350__90 " + $d);
end

rule "bath_rule_350__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_350__91 " + $d);
end

rule "bath_rule_350__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_350__92 " + $d);
end

rule "bath_rule_350__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_350__93 " + $d);
end

rule "bath_rule_350__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_350__94 " + $d);
end

rule "bath_rule_350__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_350__95 " + $d);
end

rule "bath_rule_350__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_350__96 " + $d);
end

rule "bath_rule_350__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_350__97 " + $d);
end

rule "bath_rule_350__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_350__98 " + $d);
end

rule "bath_rule_350__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_350__99 " + $d);
end

rule "bath_rule_350__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_350__100 " + $d);
end

