rule "bath_rule_375__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_375__0 " + $d);
end

rule "bath_rule_375__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_375__1 " + $d);
end

rule "bath_rule_375__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_375__2 " + $d);
end

rule "bath_rule_375__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_375__3 " + $d);
end

rule "bath_rule_375__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_375__4 " + $d);
end

rule "bath_rule_375__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_375__5 " + $d);
end

rule "bath_rule_375__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_375__6 " + $d);
end

rule "bath_rule_375__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_375__7 " + $d);
end

rule "bath_rule_375__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_375__8 " + $d);
end

rule "bath_rule_375__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_375__9 " + $d);
end

rule "bath_rule_375__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_375__10 " + $d);
end

rule "bath_rule_375__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_375__11 " + $d);
end

rule "bath_rule_375__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_375__12 " + $d);
end

rule "bath_rule_375__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_375__13 " + $d);
end

rule "bath_rule_375__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_375__14 " + $d);
end

rule "bath_rule_375__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_375__15 " + $d);
end

rule "bath_rule_375__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_375__16 " + $d);
end

rule "bath_rule_375__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_375__17 " + $d);
end

rule "bath_rule_375__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_375__18 " + $d);
end

rule "bath_rule_375__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_375__19 " + $d);
end

rule "bath_rule_375__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_375__20 " + $d);
end

rule "bath_rule_375__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_375__21 " + $d);
end

rule "bath_rule_375__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_375__22 " + $d);
end

rule "bath_rule_375__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_375__23 " + $d);
end

rule "bath_rule_375__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_375__24 " + $d);
end

rule "bath_rule_375__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_375__25 " + $d);
end

rule "bath_rule_375__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_375__26 " + $d);
end

rule "bath_rule_375__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_375__27 " + $d);
end

rule "bath_rule_375__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_375__28 " + $d);
end

rule "bath_rule_375__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_375__29 " + $d);
end

rule "bath_rule_375__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_375__30 " + $d);
end

rule "bath_rule_375__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_375__31 " + $d);
end

rule "bath_rule_375__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_375__32 " + $d);
end

rule "bath_rule_375__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_375__33 " + $d);
end

rule "bath_rule_375__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_375__34 " + $d);
end

rule "bath_rule_375__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_375__35 " + $d);
end

rule "bath_rule_375__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_375__36 " + $d);
end

rule "bath_rule_375__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_375__37 " + $d);
end

rule "bath_rule_375__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_375__38 " + $d);
end

rule "bath_rule_375__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_375__39 " + $d);
end

rule "bath_rule_375__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_375__40 " + $d);
end

rule "bath_rule_375__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_375__41 " + $d);
end

rule "bath_rule_375__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_375__42 " + $d);
end

rule "bath_rule_375__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_375__43 " + $d);
end

rule "bath_rule_375__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_375__44 " + $d);
end

rule "bath_rule_375__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_375__45 " + $d);
end

rule "bath_rule_375__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_375__46 " + $d);
end

rule "bath_rule_375__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_375__47 " + $d);
end

rule "bath_rule_375__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_375__48 " + $d);
end

rule "bath_rule_375__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_375__49 " + $d);
end

rule "bath_rule_375__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_375__50 " + $d);
end

rule "bath_rule_375__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_375__51 " + $d);
end

rule "bath_rule_375__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_375__52 " + $d);
end

rule "bath_rule_375__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_375__53 " + $d);
end

rule "bath_rule_375__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_375__54 " + $d);
end

rule "bath_rule_375__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_375__55 " + $d);
end

rule "bath_rule_375__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_375__56 " + $d);
end

rule "bath_rule_375__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_375__57 " + $d);
end

rule "bath_rule_375__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_375__58 " + $d);
end

rule "bath_rule_375__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_375__59 " + $d);
end

rule "bath_rule_375__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_375__60 " + $d);
end

rule "bath_rule_375__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_375__61 " + $d);
end

rule "bath_rule_375__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_375__62 " + $d);
end

rule "bath_rule_375__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_375__63 " + $d);
end

rule "bath_rule_375__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_375__64 " + $d);
end

rule "bath_rule_375__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_375__65 " + $d);
end

rule "bath_rule_375__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_375__66 " + $d);
end

rule "bath_rule_375__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_375__67 " + $d);
end

rule "bath_rule_375__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_375__68 " + $d);
end

rule "bath_rule_375__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_375__69 " + $d);
end

rule "bath_rule_375__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_375__70 " + $d);
end

rule "bath_rule_375__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_375__71 " + $d);
end

rule "bath_rule_375__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_375__72 " + $d);
end

rule "bath_rule_375__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_375__73 " + $d);
end

rule "bath_rule_375__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_375__74 " + $d);
end

rule "bath_rule_375__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_375__75 " + $d);
end

rule "bath_rule_375__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_375__76 " + $d);
end

rule "bath_rule_375__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_375__77 " + $d);
end

rule "bath_rule_375__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_375__78 " + $d);
end

rule "bath_rule_375__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_375__79 " + $d);
end

rule "bath_rule_375__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_375__80 " + $d);
end

rule "bath_rule_375__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_375__81 " + $d);
end

rule "bath_rule_375__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_375__82 " + $d);
end

rule "bath_rule_375__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_375__83 " + $d);
end

rule "bath_rule_375__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_375__84 " + $d);
end

rule "bath_rule_375__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_375__85 " + $d);
end

rule "bath_rule_375__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_375__86 " + $d);
end

rule "bath_rule_375__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_375__87 " + $d);
end

rule "bath_rule_375__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_375__88 " + $d);
end

rule "bath_rule_375__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_375__89 " + $d);
end

rule "bath_rule_375__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_375__90 " + $d);
end

rule "bath_rule_375__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_375__91 " + $d);
end

rule "bath_rule_375__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_375__92 " + $d);
end

rule "bath_rule_375__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_375__93 " + $d);
end

rule "bath_rule_375__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_375__94 " + $d);
end

rule "bath_rule_375__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_375__95 " + $d);
end

rule "bath_rule_375__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_375__96 " + $d);
end

rule "bath_rule_375__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_375__97 " + $d);
end

rule "bath_rule_375__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_375__98 " + $d);
end

rule "bath_rule_375__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_375__99 " + $d);
end

rule "bath_rule_375__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_375__100 " + $d);
end

