rule "bath_rule_476__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_476__0 " + $d);
end

rule "bath_rule_476__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_476__1 " + $d);
end

rule "bath_rule_476__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_476__2 " + $d);
end

rule "bath_rule_476__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_476__3 " + $d);
end

rule "bath_rule_476__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_476__4 " + $d);
end

rule "bath_rule_476__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_476__5 " + $d);
end

rule "bath_rule_476__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_476__6 " + $d);
end

rule "bath_rule_476__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_476__7 " + $d);
end

rule "bath_rule_476__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_476__8 " + $d);
end

rule "bath_rule_476__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_476__9 " + $d);
end

rule "bath_rule_476__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_476__10 " + $d);
end

rule "bath_rule_476__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_476__11 " + $d);
end

rule "bath_rule_476__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_476__12 " + $d);
end

rule "bath_rule_476__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_476__13 " + $d);
end

rule "bath_rule_476__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_476__14 " + $d);
end

rule "bath_rule_476__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_476__15 " + $d);
end

rule "bath_rule_476__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_476__16 " + $d);
end

rule "bath_rule_476__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_476__17 " + $d);
end

rule "bath_rule_476__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_476__18 " + $d);
end

rule "bath_rule_476__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_476__19 " + $d);
end

rule "bath_rule_476__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_476__20 " + $d);
end

rule "bath_rule_476__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_476__21 " + $d);
end

rule "bath_rule_476__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_476__22 " + $d);
end

rule "bath_rule_476__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_476__23 " + $d);
end

rule "bath_rule_476__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_476__24 " + $d);
end

rule "bath_rule_476__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_476__25 " + $d);
end

rule "bath_rule_476__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_476__26 " + $d);
end

rule "bath_rule_476__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_476__27 " + $d);
end

rule "bath_rule_476__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_476__28 " + $d);
end

rule "bath_rule_476__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_476__29 " + $d);
end

rule "bath_rule_476__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_476__30 " + $d);
end

rule "bath_rule_476__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_476__31 " + $d);
end

rule "bath_rule_476__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_476__32 " + $d);
end

rule "bath_rule_476__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_476__33 " + $d);
end

rule "bath_rule_476__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_476__34 " + $d);
end

rule "bath_rule_476__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_476__35 " + $d);
end

rule "bath_rule_476__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_476__36 " + $d);
end

rule "bath_rule_476__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_476__37 " + $d);
end

rule "bath_rule_476__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_476__38 " + $d);
end

rule "bath_rule_476__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_476__39 " + $d);
end

rule "bath_rule_476__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_476__40 " + $d);
end

rule "bath_rule_476__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_476__41 " + $d);
end

rule "bath_rule_476__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_476__42 " + $d);
end

rule "bath_rule_476__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_476__43 " + $d);
end

rule "bath_rule_476__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_476__44 " + $d);
end

rule "bath_rule_476__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_476__45 " + $d);
end

rule "bath_rule_476__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_476__46 " + $d);
end

rule "bath_rule_476__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_476__47 " + $d);
end

rule "bath_rule_476__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_476__48 " + $d);
end

rule "bath_rule_476__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_476__49 " + $d);
end

rule "bath_rule_476__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_476__50 " + $d);
end

rule "bath_rule_476__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_476__51 " + $d);
end

rule "bath_rule_476__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_476__52 " + $d);
end

rule "bath_rule_476__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_476__53 " + $d);
end

rule "bath_rule_476__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_476__54 " + $d);
end

rule "bath_rule_476__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_476__55 " + $d);
end

rule "bath_rule_476__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_476__56 " + $d);
end

rule "bath_rule_476__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_476__57 " + $d);
end

rule "bath_rule_476__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_476__58 " + $d);
end

rule "bath_rule_476__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_476__59 " + $d);
end

rule "bath_rule_476__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_476__60 " + $d);
end

rule "bath_rule_476__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_476__61 " + $d);
end

rule "bath_rule_476__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_476__62 " + $d);
end

rule "bath_rule_476__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_476__63 " + $d);
end

rule "bath_rule_476__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_476__64 " + $d);
end

rule "bath_rule_476__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_476__65 " + $d);
end

rule "bath_rule_476__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_476__66 " + $d);
end

rule "bath_rule_476__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_476__67 " + $d);
end

rule "bath_rule_476__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_476__68 " + $d);
end

rule "bath_rule_476__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_476__69 " + $d);
end

rule "bath_rule_476__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_476__70 " + $d);
end

rule "bath_rule_476__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_476__71 " + $d);
end

rule "bath_rule_476__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_476__72 " + $d);
end

rule "bath_rule_476__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_476__73 " + $d);
end

rule "bath_rule_476__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_476__74 " + $d);
end

rule "bath_rule_476__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_476__75 " + $d);
end

rule "bath_rule_476__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_476__76 " + $d);
end

rule "bath_rule_476__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_476__77 " + $d);
end

rule "bath_rule_476__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_476__78 " + $d);
end

rule "bath_rule_476__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_476__79 " + $d);
end

rule "bath_rule_476__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_476__80 " + $d);
end

rule "bath_rule_476__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_476__81 " + $d);
end

rule "bath_rule_476__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_476__82 " + $d);
end

rule "bath_rule_476__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_476__83 " + $d);
end

rule "bath_rule_476__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_476__84 " + $d);
end

rule "bath_rule_476__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_476__85 " + $d);
end

rule "bath_rule_476__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_476__86 " + $d);
end

rule "bath_rule_476__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_476__87 " + $d);
end

rule "bath_rule_476__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_476__88 " + $d);
end

rule "bath_rule_476__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_476__89 " + $d);
end

rule "bath_rule_476__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_476__90 " + $d);
end

rule "bath_rule_476__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_476__91 " + $d);
end

rule "bath_rule_476__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_476__92 " + $d);
end

rule "bath_rule_476__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_476__93 " + $d);
end

rule "bath_rule_476__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_476__94 " + $d);
end

rule "bath_rule_476__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_476__95 " + $d);
end

rule "bath_rule_476__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_476__96 " + $d);
end

rule "bath_rule_476__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_476__97 " + $d);
end

rule "bath_rule_476__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_476__98 " + $d);
end

rule "bath_rule_476__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_476__99 " + $d);
end

rule "bath_rule_476__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_476__100 " + $d);
end

