rule "bath_rule_510__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_510__0 " + $d);
end

rule "bath_rule_510__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_510__1 " + $d);
end

rule "bath_rule_510__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_510__2 " + $d);
end

rule "bath_rule_510__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_510__3 " + $d);
end

rule "bath_rule_510__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_510__4 " + $d);
end

rule "bath_rule_510__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_510__5 " + $d);
end

rule "bath_rule_510__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_510__6 " + $d);
end

rule "bath_rule_510__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_510__7 " + $d);
end

rule "bath_rule_510__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_510__8 " + $d);
end

rule "bath_rule_510__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_510__9 " + $d);
end

rule "bath_rule_510__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_510__10 " + $d);
end

rule "bath_rule_510__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_510__11 " + $d);
end

rule "bath_rule_510__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_510__12 " + $d);
end

rule "bath_rule_510__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_510__13 " + $d);
end

rule "bath_rule_510__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_510__14 " + $d);
end

rule "bath_rule_510__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_510__15 " + $d);
end

rule "bath_rule_510__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_510__16 " + $d);
end

rule "bath_rule_510__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_510__17 " + $d);
end

rule "bath_rule_510__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_510__18 " + $d);
end

rule "bath_rule_510__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_510__19 " + $d);
end

rule "bath_rule_510__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_510__20 " + $d);
end

rule "bath_rule_510__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_510__21 " + $d);
end

rule "bath_rule_510__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_510__22 " + $d);
end

rule "bath_rule_510__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_510__23 " + $d);
end

rule "bath_rule_510__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_510__24 " + $d);
end

rule "bath_rule_510__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_510__25 " + $d);
end

rule "bath_rule_510__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_510__26 " + $d);
end

rule "bath_rule_510__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_510__27 " + $d);
end

rule "bath_rule_510__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_510__28 " + $d);
end

rule "bath_rule_510__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_510__29 " + $d);
end

rule "bath_rule_510__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_510__30 " + $d);
end

rule "bath_rule_510__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_510__31 " + $d);
end

rule "bath_rule_510__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_510__32 " + $d);
end

rule "bath_rule_510__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_510__33 " + $d);
end

rule "bath_rule_510__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_510__34 " + $d);
end

rule "bath_rule_510__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_510__35 " + $d);
end

rule "bath_rule_510__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_510__36 " + $d);
end

rule "bath_rule_510__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_510__37 " + $d);
end

rule "bath_rule_510__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_510__38 " + $d);
end

rule "bath_rule_510__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_510__39 " + $d);
end

rule "bath_rule_510__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_510__40 " + $d);
end

rule "bath_rule_510__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_510__41 " + $d);
end

rule "bath_rule_510__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_510__42 " + $d);
end

rule "bath_rule_510__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_510__43 " + $d);
end

rule "bath_rule_510__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_510__44 " + $d);
end

rule "bath_rule_510__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_510__45 " + $d);
end

rule "bath_rule_510__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_510__46 " + $d);
end

rule "bath_rule_510__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_510__47 " + $d);
end

rule "bath_rule_510__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_510__48 " + $d);
end

rule "bath_rule_510__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_510__49 " + $d);
end

rule "bath_rule_510__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_510__50 " + $d);
end

rule "bath_rule_510__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_510__51 " + $d);
end

rule "bath_rule_510__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_510__52 " + $d);
end

rule "bath_rule_510__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_510__53 " + $d);
end

rule "bath_rule_510__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_510__54 " + $d);
end

rule "bath_rule_510__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_510__55 " + $d);
end

rule "bath_rule_510__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_510__56 " + $d);
end

rule "bath_rule_510__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_510__57 " + $d);
end

rule "bath_rule_510__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_510__58 " + $d);
end

rule "bath_rule_510__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_510__59 " + $d);
end

rule "bath_rule_510__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_510__60 " + $d);
end

rule "bath_rule_510__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_510__61 " + $d);
end

rule "bath_rule_510__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_510__62 " + $d);
end

rule "bath_rule_510__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_510__63 " + $d);
end

rule "bath_rule_510__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_510__64 " + $d);
end

rule "bath_rule_510__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_510__65 " + $d);
end

rule "bath_rule_510__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_510__66 " + $d);
end

rule "bath_rule_510__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_510__67 " + $d);
end

rule "bath_rule_510__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_510__68 " + $d);
end

rule "bath_rule_510__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_510__69 " + $d);
end

rule "bath_rule_510__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_510__70 " + $d);
end

rule "bath_rule_510__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_510__71 " + $d);
end

rule "bath_rule_510__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_510__72 " + $d);
end

rule "bath_rule_510__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_510__73 " + $d);
end

rule "bath_rule_510__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_510__74 " + $d);
end

rule "bath_rule_510__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_510__75 " + $d);
end

rule "bath_rule_510__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_510__76 " + $d);
end

rule "bath_rule_510__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_510__77 " + $d);
end

rule "bath_rule_510__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_510__78 " + $d);
end

rule "bath_rule_510__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_510__79 " + $d);
end

rule "bath_rule_510__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_510__80 " + $d);
end

rule "bath_rule_510__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_510__81 " + $d);
end

rule "bath_rule_510__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_510__82 " + $d);
end

rule "bath_rule_510__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_510__83 " + $d);
end

rule "bath_rule_510__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_510__84 " + $d);
end

rule "bath_rule_510__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_510__85 " + $d);
end

rule "bath_rule_510__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_510__86 " + $d);
end

rule "bath_rule_510__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_510__87 " + $d);
end

rule "bath_rule_510__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_510__88 " + $d);
end

rule "bath_rule_510__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_510__89 " + $d);
end

rule "bath_rule_510__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_510__90 " + $d);
end

rule "bath_rule_510__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_510__91 " + $d);
end

rule "bath_rule_510__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_510__92 " + $d);
end

rule "bath_rule_510__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_510__93 " + $d);
end

rule "bath_rule_510__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_510__94 " + $d);
end

rule "bath_rule_510__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_510__95 " + $d);
end

rule "bath_rule_510__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_510__96 " + $d);
end

rule "bath_rule_510__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_510__97 " + $d);
end

rule "bath_rule_510__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_510__98 " + $d);
end

rule "bath_rule_510__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_510__99 " + $d);
end

rule "bath_rule_510__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_510__100 " + $d);
end

