rule "bath_rule_635__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_635__0 " + $d);
end

rule "bath_rule_635__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_635__1 " + $d);
end

rule "bath_rule_635__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_635__2 " + $d);
end

rule "bath_rule_635__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_635__3 " + $d);
end

rule "bath_rule_635__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_635__4 " + $d);
end

rule "bath_rule_635__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_635__5 " + $d);
end

rule "bath_rule_635__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_635__6 " + $d);
end

rule "bath_rule_635__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_635__7 " + $d);
end

rule "bath_rule_635__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_635__8 " + $d);
end

rule "bath_rule_635__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_635__9 " + $d);
end

rule "bath_rule_635__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_635__10 " + $d);
end

rule "bath_rule_635__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_635__11 " + $d);
end

rule "bath_rule_635__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_635__12 " + $d);
end

rule "bath_rule_635__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_635__13 " + $d);
end

rule "bath_rule_635__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_635__14 " + $d);
end

rule "bath_rule_635__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_635__15 " + $d);
end

rule "bath_rule_635__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_635__16 " + $d);
end

rule "bath_rule_635__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_635__17 " + $d);
end

rule "bath_rule_635__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_635__18 " + $d);
end

rule "bath_rule_635__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_635__19 " + $d);
end

rule "bath_rule_635__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_635__20 " + $d);
end

rule "bath_rule_635__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_635__21 " + $d);
end

rule "bath_rule_635__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_635__22 " + $d);
end

rule "bath_rule_635__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_635__23 " + $d);
end

rule "bath_rule_635__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_635__24 " + $d);
end

rule "bath_rule_635__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_635__25 " + $d);
end

rule "bath_rule_635__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_635__26 " + $d);
end

rule "bath_rule_635__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_635__27 " + $d);
end

rule "bath_rule_635__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_635__28 " + $d);
end

rule "bath_rule_635__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_635__29 " + $d);
end

rule "bath_rule_635__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_635__30 " + $d);
end

rule "bath_rule_635__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_635__31 " + $d);
end

rule "bath_rule_635__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_635__32 " + $d);
end

rule "bath_rule_635__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_635__33 " + $d);
end

rule "bath_rule_635__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_635__34 " + $d);
end

rule "bath_rule_635__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_635__35 " + $d);
end

rule "bath_rule_635__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_635__36 " + $d);
end

rule "bath_rule_635__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_635__37 " + $d);
end

rule "bath_rule_635__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_635__38 " + $d);
end

rule "bath_rule_635__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_635__39 " + $d);
end

rule "bath_rule_635__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_635__40 " + $d);
end

rule "bath_rule_635__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_635__41 " + $d);
end

rule "bath_rule_635__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_635__42 " + $d);
end

rule "bath_rule_635__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_635__43 " + $d);
end

rule "bath_rule_635__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_635__44 " + $d);
end

rule "bath_rule_635__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_635__45 " + $d);
end

rule "bath_rule_635__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_635__46 " + $d);
end

rule "bath_rule_635__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_635__47 " + $d);
end

rule "bath_rule_635__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_635__48 " + $d);
end

rule "bath_rule_635__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_635__49 " + $d);
end

rule "bath_rule_635__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_635__50 " + $d);
end

rule "bath_rule_635__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_635__51 " + $d);
end

rule "bath_rule_635__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_635__52 " + $d);
end

rule "bath_rule_635__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_635__53 " + $d);
end

rule "bath_rule_635__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_635__54 " + $d);
end

rule "bath_rule_635__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_635__55 " + $d);
end

rule "bath_rule_635__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_635__56 " + $d);
end

rule "bath_rule_635__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_635__57 " + $d);
end

rule "bath_rule_635__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_635__58 " + $d);
end

rule "bath_rule_635__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_635__59 " + $d);
end

rule "bath_rule_635__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_635__60 " + $d);
end

rule "bath_rule_635__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_635__61 " + $d);
end

rule "bath_rule_635__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_635__62 " + $d);
end

rule "bath_rule_635__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_635__63 " + $d);
end

rule "bath_rule_635__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_635__64 " + $d);
end

rule "bath_rule_635__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_635__65 " + $d);
end

rule "bath_rule_635__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_635__66 " + $d);
end

rule "bath_rule_635__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_635__67 " + $d);
end

rule "bath_rule_635__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_635__68 " + $d);
end

rule "bath_rule_635__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_635__69 " + $d);
end

rule "bath_rule_635__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_635__70 " + $d);
end

rule "bath_rule_635__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_635__71 " + $d);
end

rule "bath_rule_635__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_635__72 " + $d);
end

rule "bath_rule_635__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_635__73 " + $d);
end

rule "bath_rule_635__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_635__74 " + $d);
end

rule "bath_rule_635__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_635__75 " + $d);
end

rule "bath_rule_635__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_635__76 " + $d);
end

rule "bath_rule_635__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_635__77 " + $d);
end

rule "bath_rule_635__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_635__78 " + $d);
end

rule "bath_rule_635__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_635__79 " + $d);
end

rule "bath_rule_635__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_635__80 " + $d);
end

rule "bath_rule_635__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_635__81 " + $d);
end

rule "bath_rule_635__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_635__82 " + $d);
end

rule "bath_rule_635__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_635__83 " + $d);
end

rule "bath_rule_635__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_635__84 " + $d);
end

rule "bath_rule_635__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_635__85 " + $d);
end

rule "bath_rule_635__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_635__86 " + $d);
end

rule "bath_rule_635__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_635__87 " + $d);
end

rule "bath_rule_635__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_635__88 " + $d);
end

rule "bath_rule_635__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_635__89 " + $d);
end

rule "bath_rule_635__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_635__90 " + $d);
end

rule "bath_rule_635__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_635__91 " + $d);
end

rule "bath_rule_635__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_635__92 " + $d);
end

rule "bath_rule_635__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_635__93 " + $d);
end

rule "bath_rule_635__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_635__94 " + $d);
end

rule "bath_rule_635__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_635__95 " + $d);
end

rule "bath_rule_635__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_635__96 " + $d);
end

rule "bath_rule_635__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_635__97 " + $d);
end

rule "bath_rule_635__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_635__98 " + $d);
end

rule "bath_rule_635__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_635__99 " + $d);
end

rule "bath_rule_635__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_635__100 " + $d);
end

