rule "bath_rule_608__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_608__0 " + $d);
end

rule "bath_rule_608__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_608__1 " + $d);
end

rule "bath_rule_608__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_608__2 " + $d);
end

rule "bath_rule_608__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_608__3 " + $d);
end

rule "bath_rule_608__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_608__4 " + $d);
end

rule "bath_rule_608__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_608__5 " + $d);
end

rule "bath_rule_608__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_608__6 " + $d);
end

rule "bath_rule_608__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_608__7 " + $d);
end

rule "bath_rule_608__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_608__8 " + $d);
end

rule "bath_rule_608__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_608__9 " + $d);
end

rule "bath_rule_608__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_608__10 " + $d);
end

rule "bath_rule_608__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_608__11 " + $d);
end

rule "bath_rule_608__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_608__12 " + $d);
end

rule "bath_rule_608__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_608__13 " + $d);
end

rule "bath_rule_608__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_608__14 " + $d);
end

rule "bath_rule_608__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_608__15 " + $d);
end

rule "bath_rule_608__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_608__16 " + $d);
end

rule "bath_rule_608__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_608__17 " + $d);
end

rule "bath_rule_608__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_608__18 " + $d);
end

rule "bath_rule_608__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_608__19 " + $d);
end

rule "bath_rule_608__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_608__20 " + $d);
end

rule "bath_rule_608__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_608__21 " + $d);
end

rule "bath_rule_608__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_608__22 " + $d);
end

rule "bath_rule_608__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_608__23 " + $d);
end

rule "bath_rule_608__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_608__24 " + $d);
end

rule "bath_rule_608__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_608__25 " + $d);
end

rule "bath_rule_608__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_608__26 " + $d);
end

rule "bath_rule_608__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_608__27 " + $d);
end

rule "bath_rule_608__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_608__28 " + $d);
end

rule "bath_rule_608__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_608__29 " + $d);
end

rule "bath_rule_608__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_608__30 " + $d);
end

rule "bath_rule_608__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_608__31 " + $d);
end

rule "bath_rule_608__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_608__32 " + $d);
end

rule "bath_rule_608__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_608__33 " + $d);
end

rule "bath_rule_608__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_608__34 " + $d);
end

rule "bath_rule_608__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_608__35 " + $d);
end

rule "bath_rule_608__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_608__36 " + $d);
end

rule "bath_rule_608__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_608__37 " + $d);
end

rule "bath_rule_608__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_608__38 " + $d);
end

rule "bath_rule_608__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_608__39 " + $d);
end

rule "bath_rule_608__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_608__40 " + $d);
end

rule "bath_rule_608__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_608__41 " + $d);
end

rule "bath_rule_608__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_608__42 " + $d);
end

rule "bath_rule_608__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_608__43 " + $d);
end

rule "bath_rule_608__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_608__44 " + $d);
end

rule "bath_rule_608__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_608__45 " + $d);
end

rule "bath_rule_608__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_608__46 " + $d);
end

rule "bath_rule_608__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_608__47 " + $d);
end

rule "bath_rule_608__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_608__48 " + $d);
end

rule "bath_rule_608__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_608__49 " + $d);
end

rule "bath_rule_608__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_608__50 " + $d);
end

rule "bath_rule_608__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_608__51 " + $d);
end

rule "bath_rule_608__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_608__52 " + $d);
end

rule "bath_rule_608__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_608__53 " + $d);
end

rule "bath_rule_608__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_608__54 " + $d);
end

rule "bath_rule_608__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_608__55 " + $d);
end

rule "bath_rule_608__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_608__56 " + $d);
end

rule "bath_rule_608__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_608__57 " + $d);
end

rule "bath_rule_608__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_608__58 " + $d);
end

rule "bath_rule_608__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_608__59 " + $d);
end

rule "bath_rule_608__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_608__60 " + $d);
end

rule "bath_rule_608__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_608__61 " + $d);
end

rule "bath_rule_608__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_608__62 " + $d);
end

rule "bath_rule_608__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_608__63 " + $d);
end

rule "bath_rule_608__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_608__64 " + $d);
end

rule "bath_rule_608__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_608__65 " + $d);
end

rule "bath_rule_608__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_608__66 " + $d);
end

rule "bath_rule_608__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_608__67 " + $d);
end

rule "bath_rule_608__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_608__68 " + $d);
end

rule "bath_rule_608__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_608__69 " + $d);
end

rule "bath_rule_608__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_608__70 " + $d);
end

rule "bath_rule_608__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_608__71 " + $d);
end

rule "bath_rule_608__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_608__72 " + $d);
end

rule "bath_rule_608__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_608__73 " + $d);
end

rule "bath_rule_608__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_608__74 " + $d);
end

rule "bath_rule_608__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_608__75 " + $d);
end

rule "bath_rule_608__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_608__76 " + $d);
end

rule "bath_rule_608__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_608__77 " + $d);
end

rule "bath_rule_608__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_608__78 " + $d);
end

rule "bath_rule_608__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_608__79 " + $d);
end

rule "bath_rule_608__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_608__80 " + $d);
end

rule "bath_rule_608__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_608__81 " + $d);
end

rule "bath_rule_608__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_608__82 " + $d);
end

rule "bath_rule_608__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_608__83 " + $d);
end

rule "bath_rule_608__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_608__84 " + $d);
end

rule "bath_rule_608__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_608__85 " + $d);
end

rule "bath_rule_608__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_608__86 " + $d);
end

rule "bath_rule_608__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_608__87 " + $d);
end

rule "bath_rule_608__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_608__88 " + $d);
end

rule "bath_rule_608__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_608__89 " + $d);
end

rule "bath_rule_608__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_608__90 " + $d);
end

rule "bath_rule_608__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_608__91 " + $d);
end

rule "bath_rule_608__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_608__92 " + $d);
end

rule "bath_rule_608__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_608__93 " + $d);
end

rule "bath_rule_608__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_608__94 " + $d);
end

rule "bath_rule_608__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_608__95 " + $d);
end

rule "bath_rule_608__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_608__96 " + $d);
end

rule "bath_rule_608__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_608__97 " + $d);
end

rule "bath_rule_608__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_608__98 " + $d);
end

rule "bath_rule_608__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_608__99 " + $d);
end

rule "bath_rule_608__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_608__100 " + $d);
end

