rule "bath_rule_602__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_602__0 " + $d);
end

rule "bath_rule_602__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_602__1 " + $d);
end

rule "bath_rule_602__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_602__2 " + $d);
end

rule "bath_rule_602__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_602__3 " + $d);
end

rule "bath_rule_602__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_602__4 " + $d);
end

rule "bath_rule_602__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_602__5 " + $d);
end

rule "bath_rule_602__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_602__6 " + $d);
end

rule "bath_rule_602__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_602__7 " + $d);
end

rule "bath_rule_602__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_602__8 " + $d);
end

rule "bath_rule_602__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_602__9 " + $d);
end

rule "bath_rule_602__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_602__10 " + $d);
end

rule "bath_rule_602__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_602__11 " + $d);
end

rule "bath_rule_602__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_602__12 " + $d);
end

rule "bath_rule_602__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_602__13 " + $d);
end

rule "bath_rule_602__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_602__14 " + $d);
end

rule "bath_rule_602__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_602__15 " + $d);
end

rule "bath_rule_602__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_602__16 " + $d);
end

rule "bath_rule_602__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_602__17 " + $d);
end

rule "bath_rule_602__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_602__18 " + $d);
end

rule "bath_rule_602__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_602__19 " + $d);
end

rule "bath_rule_602__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_602__20 " + $d);
end

rule "bath_rule_602__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_602__21 " + $d);
end

rule "bath_rule_602__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_602__22 " + $d);
end

rule "bath_rule_602__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_602__23 " + $d);
end

rule "bath_rule_602__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_602__24 " + $d);
end

rule "bath_rule_602__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_602__25 " + $d);
end

rule "bath_rule_602__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_602__26 " + $d);
end

rule "bath_rule_602__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_602__27 " + $d);
end

rule "bath_rule_602__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_602__28 " + $d);
end

rule "bath_rule_602__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_602__29 " + $d);
end

rule "bath_rule_602__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_602__30 " + $d);
end

rule "bath_rule_602__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_602__31 " + $d);
end

rule "bath_rule_602__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_602__32 " + $d);
end

rule "bath_rule_602__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_602__33 " + $d);
end

rule "bath_rule_602__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_602__34 " + $d);
end

rule "bath_rule_602__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_602__35 " + $d);
end

rule "bath_rule_602__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_602__36 " + $d);
end

rule "bath_rule_602__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_602__37 " + $d);
end

rule "bath_rule_602__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_602__38 " + $d);
end

rule "bath_rule_602__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_602__39 " + $d);
end

rule "bath_rule_602__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_602__40 " + $d);
end

rule "bath_rule_602__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_602__41 " + $d);
end

rule "bath_rule_602__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_602__42 " + $d);
end

rule "bath_rule_602__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_602__43 " + $d);
end

rule "bath_rule_602__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_602__44 " + $d);
end

rule "bath_rule_602__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_602__45 " + $d);
end

rule "bath_rule_602__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_602__46 " + $d);
end

rule "bath_rule_602__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_602__47 " + $d);
end

rule "bath_rule_602__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_602__48 " + $d);
end

rule "bath_rule_602__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_602__49 " + $d);
end

rule "bath_rule_602__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_602__50 " + $d);
end

rule "bath_rule_602__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_602__51 " + $d);
end

rule "bath_rule_602__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_602__52 " + $d);
end

rule "bath_rule_602__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_602__53 " + $d);
end

rule "bath_rule_602__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_602__54 " + $d);
end

rule "bath_rule_602__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_602__55 " + $d);
end

rule "bath_rule_602__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_602__56 " + $d);
end

rule "bath_rule_602__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_602__57 " + $d);
end

rule "bath_rule_602__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_602__58 " + $d);
end

rule "bath_rule_602__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_602__59 " + $d);
end

rule "bath_rule_602__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_602__60 " + $d);
end

rule "bath_rule_602__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_602__61 " + $d);
end

rule "bath_rule_602__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_602__62 " + $d);
end

rule "bath_rule_602__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_602__63 " + $d);
end

rule "bath_rule_602__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_602__64 " + $d);
end

rule "bath_rule_602__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_602__65 " + $d);
end

rule "bath_rule_602__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_602__66 " + $d);
end

rule "bath_rule_602__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_602__67 " + $d);
end

rule "bath_rule_602__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_602__68 " + $d);
end

rule "bath_rule_602__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_602__69 " + $d);
end

rule "bath_rule_602__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_602__70 " + $d);
end

rule "bath_rule_602__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_602__71 " + $d);
end

rule "bath_rule_602__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_602__72 " + $d);
end

rule "bath_rule_602__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_602__73 " + $d);
end

rule "bath_rule_602__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_602__74 " + $d);
end

rule "bath_rule_602__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_602__75 " + $d);
end

rule "bath_rule_602__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_602__76 " + $d);
end

rule "bath_rule_602__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_602__77 " + $d);
end

rule "bath_rule_602__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_602__78 " + $d);
end

rule "bath_rule_602__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_602__79 " + $d);
end

rule "bath_rule_602__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_602__80 " + $d);
end

rule "bath_rule_602__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_602__81 " + $d);
end

rule "bath_rule_602__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_602__82 " + $d);
end

rule "bath_rule_602__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_602__83 " + $d);
end

rule "bath_rule_602__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_602__84 " + $d);
end

rule "bath_rule_602__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_602__85 " + $d);
end

rule "bath_rule_602__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_602__86 " + $d);
end

rule "bath_rule_602__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_602__87 " + $d);
end

rule "bath_rule_602__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_602__88 " + $d);
end

rule "bath_rule_602__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_602__89 " + $d);
end

rule "bath_rule_602__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_602__90 " + $d);
end

rule "bath_rule_602__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_602__91 " + $d);
end

rule "bath_rule_602__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_602__92 " + $d);
end

rule "bath_rule_602__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_602__93 " + $d);
end

rule "bath_rule_602__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_602__94 " + $d);
end

rule "bath_rule_602__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_602__95 " + $d);
end

rule "bath_rule_602__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_602__96 " + $d);
end

rule "bath_rule_602__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_602__97 " + $d);
end

rule "bath_rule_602__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_602__98 " + $d);
end

rule "bath_rule_602__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_602__99 " + $d);
end

rule "bath_rule_602__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_602__100 " + $d);
end

