rule "bath_rule_61__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_61__0 " + $d);
end

rule "bath_rule_61__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_61__1 " + $d);
end

rule "bath_rule_61__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_61__2 " + $d);
end

rule "bath_rule_61__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_61__3 " + $d);
end

rule "bath_rule_61__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_61__4 " + $d);
end

rule "bath_rule_61__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_61__5 " + $d);
end

rule "bath_rule_61__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_61__6 " + $d);
end

rule "bath_rule_61__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_61__7 " + $d);
end

rule "bath_rule_61__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_61__8 " + $d);
end

rule "bath_rule_61__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_61__9 " + $d);
end

rule "bath_rule_61__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_61__10 " + $d);
end

rule "bath_rule_61__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_61__11 " + $d);
end

rule "bath_rule_61__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_61__12 " + $d);
end

rule "bath_rule_61__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_61__13 " + $d);
end

rule "bath_rule_61__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_61__14 " + $d);
end

rule "bath_rule_61__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_61__15 " + $d);
end

rule "bath_rule_61__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_61__16 " + $d);
end

rule "bath_rule_61__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_61__17 " + $d);
end

rule "bath_rule_61__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_61__18 " + $d);
end

rule "bath_rule_61__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_61__19 " + $d);
end

rule "bath_rule_61__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_61__20 " + $d);
end

rule "bath_rule_61__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_61__21 " + $d);
end

rule "bath_rule_61__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_61__22 " + $d);
end

rule "bath_rule_61__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_61__23 " + $d);
end

rule "bath_rule_61__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_61__24 " + $d);
end

rule "bath_rule_61__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_61__25 " + $d);
end

rule "bath_rule_61__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_61__26 " + $d);
end

rule "bath_rule_61__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_61__27 " + $d);
end

rule "bath_rule_61__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_61__28 " + $d);
end

rule "bath_rule_61__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_61__29 " + $d);
end

rule "bath_rule_61__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_61__30 " + $d);
end

rule "bath_rule_61__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_61__31 " + $d);
end

rule "bath_rule_61__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_61__32 " + $d);
end

rule "bath_rule_61__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_61__33 " + $d);
end

rule "bath_rule_61__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_61__34 " + $d);
end

rule "bath_rule_61__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_61__35 " + $d);
end

rule "bath_rule_61__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_61__36 " + $d);
end

rule "bath_rule_61__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_61__37 " + $d);
end

rule "bath_rule_61__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_61__38 " + $d);
end

rule "bath_rule_61__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_61__39 " + $d);
end

rule "bath_rule_61__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_61__40 " + $d);
end

rule "bath_rule_61__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_61__41 " + $d);
end

rule "bath_rule_61__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_61__42 " + $d);
end

rule "bath_rule_61__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_61__43 " + $d);
end

rule "bath_rule_61__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_61__44 " + $d);
end

rule "bath_rule_61__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_61__45 " + $d);
end

rule "bath_rule_61__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_61__46 " + $d);
end

rule "bath_rule_61__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_61__47 " + $d);
end

rule "bath_rule_61__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_61__48 " + $d);
end

rule "bath_rule_61__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_61__49 " + $d);
end

rule "bath_rule_61__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_61__50 " + $d);
end

rule "bath_rule_61__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_61__51 " + $d);
end

rule "bath_rule_61__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_61__52 " + $d);
end

rule "bath_rule_61__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_61__53 " + $d);
end

rule "bath_rule_61__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_61__54 " + $d);
end

rule "bath_rule_61__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_61__55 " + $d);
end

rule "bath_rule_61__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_61__56 " + $d);
end

rule "bath_rule_61__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_61__57 " + $d);
end

rule "bath_rule_61__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_61__58 " + $d);
end

rule "bath_rule_61__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_61__59 " + $d);
end

rule "bath_rule_61__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_61__60 " + $d);
end

rule "bath_rule_61__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_61__61 " + $d);
end

rule "bath_rule_61__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_61__62 " + $d);
end

rule "bath_rule_61__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_61__63 " + $d);
end

rule "bath_rule_61__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_61__64 " + $d);
end

rule "bath_rule_61__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_61__65 " + $d);
end

rule "bath_rule_61__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_61__66 " + $d);
end

rule "bath_rule_61__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_61__67 " + $d);
end

rule "bath_rule_61__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_61__68 " + $d);
end

rule "bath_rule_61__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_61__69 " + $d);
end

rule "bath_rule_61__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_61__70 " + $d);
end

rule "bath_rule_61__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_61__71 " + $d);
end

rule "bath_rule_61__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_61__72 " + $d);
end

rule "bath_rule_61__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_61__73 " + $d);
end

rule "bath_rule_61__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_61__74 " + $d);
end

rule "bath_rule_61__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_61__75 " + $d);
end

rule "bath_rule_61__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_61__76 " + $d);
end

rule "bath_rule_61__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_61__77 " + $d);
end

rule "bath_rule_61__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_61__78 " + $d);
end

rule "bath_rule_61__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_61__79 " + $d);
end

rule "bath_rule_61__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_61__80 " + $d);
end

rule "bath_rule_61__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_61__81 " + $d);
end

rule "bath_rule_61__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_61__82 " + $d);
end

rule "bath_rule_61__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_61__83 " + $d);
end

rule "bath_rule_61__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_61__84 " + $d);
end

rule "bath_rule_61__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_61__85 " + $d);
end

rule "bath_rule_61__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_61__86 " + $d);
end

rule "bath_rule_61__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_61__87 " + $d);
end

rule "bath_rule_61__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_61__88 " + $d);
end

rule "bath_rule_61__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_61__89 " + $d);
end

rule "bath_rule_61__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_61__90 " + $d);
end

rule "bath_rule_61__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_61__91 " + $d);
end

rule "bath_rule_61__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_61__92 " + $d);
end

rule "bath_rule_61__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_61__93 " + $d);
end

rule "bath_rule_61__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_61__94 " + $d);
end

rule "bath_rule_61__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_61__95 " + $d);
end

rule "bath_rule_61__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_61__96 " + $d);
end

rule "bath_rule_61__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_61__97 " + $d);
end

rule "bath_rule_61__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_61__98 " + $d);
end

rule "bath_rule_61__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_61__99 " + $d);
end

rule "bath_rule_61__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_61__100 " + $d);
end

