rule "bath_rule_798__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_798__0 " + $d);
end

rule "bath_rule_798__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_798__1 " + $d);
end

rule "bath_rule_798__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_798__2 " + $d);
end

rule "bath_rule_798__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_798__3 " + $d);
end

rule "bath_rule_798__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_798__4 " + $d);
end

rule "bath_rule_798__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_798__5 " + $d);
end

rule "bath_rule_798__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_798__6 " + $d);
end

rule "bath_rule_798__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_798__7 " + $d);
end

rule "bath_rule_798__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_798__8 " + $d);
end

rule "bath_rule_798__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_798__9 " + $d);
end

rule "bath_rule_798__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_798__10 " + $d);
end

rule "bath_rule_798__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_798__11 " + $d);
end

rule "bath_rule_798__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_798__12 " + $d);
end

rule "bath_rule_798__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_798__13 " + $d);
end

rule "bath_rule_798__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_798__14 " + $d);
end

rule "bath_rule_798__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_798__15 " + $d);
end

rule "bath_rule_798__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_798__16 " + $d);
end

rule "bath_rule_798__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_798__17 " + $d);
end

rule "bath_rule_798__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_798__18 " + $d);
end

rule "bath_rule_798__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_798__19 " + $d);
end

rule "bath_rule_798__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_798__20 " + $d);
end

rule "bath_rule_798__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_798__21 " + $d);
end

rule "bath_rule_798__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_798__22 " + $d);
end

rule "bath_rule_798__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_798__23 " + $d);
end

rule "bath_rule_798__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_798__24 " + $d);
end

rule "bath_rule_798__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_798__25 " + $d);
end

rule "bath_rule_798__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_798__26 " + $d);
end

rule "bath_rule_798__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_798__27 " + $d);
end

rule "bath_rule_798__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_798__28 " + $d);
end

rule "bath_rule_798__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_798__29 " + $d);
end

rule "bath_rule_798__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_798__30 " + $d);
end

rule "bath_rule_798__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_798__31 " + $d);
end

rule "bath_rule_798__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_798__32 " + $d);
end

rule "bath_rule_798__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_798__33 " + $d);
end

rule "bath_rule_798__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_798__34 " + $d);
end

rule "bath_rule_798__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_798__35 " + $d);
end

rule "bath_rule_798__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_798__36 " + $d);
end

rule "bath_rule_798__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_798__37 " + $d);
end

rule "bath_rule_798__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_798__38 " + $d);
end

rule "bath_rule_798__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_798__39 " + $d);
end

rule "bath_rule_798__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_798__40 " + $d);
end

rule "bath_rule_798__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_798__41 " + $d);
end

rule "bath_rule_798__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_798__42 " + $d);
end

rule "bath_rule_798__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_798__43 " + $d);
end

rule "bath_rule_798__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_798__44 " + $d);
end

rule "bath_rule_798__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_798__45 " + $d);
end

rule "bath_rule_798__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_798__46 " + $d);
end

rule "bath_rule_798__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_798__47 " + $d);
end

rule "bath_rule_798__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_798__48 " + $d);
end

rule "bath_rule_798__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_798__49 " + $d);
end

rule "bath_rule_798__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_798__50 " + $d);
end

rule "bath_rule_798__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_798__51 " + $d);
end

rule "bath_rule_798__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_798__52 " + $d);
end

rule "bath_rule_798__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_798__53 " + $d);
end

rule "bath_rule_798__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_798__54 " + $d);
end

rule "bath_rule_798__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_798__55 " + $d);
end

rule "bath_rule_798__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_798__56 " + $d);
end

rule "bath_rule_798__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_798__57 " + $d);
end

rule "bath_rule_798__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_798__58 " + $d);
end

rule "bath_rule_798__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_798__59 " + $d);
end

rule "bath_rule_798__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_798__60 " + $d);
end

rule "bath_rule_798__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_798__61 " + $d);
end

rule "bath_rule_798__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_798__62 " + $d);
end

rule "bath_rule_798__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_798__63 " + $d);
end

rule "bath_rule_798__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_798__64 " + $d);
end

rule "bath_rule_798__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_798__65 " + $d);
end

rule "bath_rule_798__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_798__66 " + $d);
end

rule "bath_rule_798__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_798__67 " + $d);
end

rule "bath_rule_798__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_798__68 " + $d);
end

rule "bath_rule_798__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_798__69 " + $d);
end

rule "bath_rule_798__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_798__70 " + $d);
end

rule "bath_rule_798__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_798__71 " + $d);
end

rule "bath_rule_798__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_798__72 " + $d);
end

rule "bath_rule_798__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_798__73 " + $d);
end

rule "bath_rule_798__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_798__74 " + $d);
end

rule "bath_rule_798__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_798__75 " + $d);
end

rule "bath_rule_798__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_798__76 " + $d);
end

rule "bath_rule_798__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_798__77 " + $d);
end

rule "bath_rule_798__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_798__78 " + $d);
end

rule "bath_rule_798__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_798__79 " + $d);
end

rule "bath_rule_798__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_798__80 " + $d);
end

rule "bath_rule_798__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_798__81 " + $d);
end

rule "bath_rule_798__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_798__82 " + $d);
end

rule "bath_rule_798__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_798__83 " + $d);
end

rule "bath_rule_798__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_798__84 " + $d);
end

rule "bath_rule_798__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_798__85 " + $d);
end

rule "bath_rule_798__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_798__86 " + $d);
end

rule "bath_rule_798__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_798__87 " + $d);
end

rule "bath_rule_798__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_798__88 " + $d);
end

rule "bath_rule_798__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_798__89 " + $d);
end

rule "bath_rule_798__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_798__90 " + $d);
end

rule "bath_rule_798__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_798__91 " + $d);
end

rule "bath_rule_798__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_798__92 " + $d);
end

rule "bath_rule_798__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_798__93 " + $d);
end

rule "bath_rule_798__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_798__94 " + $d);
end

rule "bath_rule_798__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_798__95 " + $d);
end

rule "bath_rule_798__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_798__96 " + $d);
end

rule "bath_rule_798__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_798__97 " + $d);
end

rule "bath_rule_798__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_798__98 " + $d);
end

rule "bath_rule_798__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_798__99 " + $d);
end

rule "bath_rule_798__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_798__100 " + $d);
end

