rule "bath_rule_723__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_723__0 " + $d);
end

rule "bath_rule_723__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_723__1 " + $d);
end

rule "bath_rule_723__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_723__2 " + $d);
end

rule "bath_rule_723__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_723__3 " + $d);
end

rule "bath_rule_723__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_723__4 " + $d);
end

rule "bath_rule_723__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_723__5 " + $d);
end

rule "bath_rule_723__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_723__6 " + $d);
end

rule "bath_rule_723__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_723__7 " + $d);
end

rule "bath_rule_723__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_723__8 " + $d);
end

rule "bath_rule_723__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_723__9 " + $d);
end

rule "bath_rule_723__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_723__10 " + $d);
end

rule "bath_rule_723__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_723__11 " + $d);
end

rule "bath_rule_723__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_723__12 " + $d);
end

rule "bath_rule_723__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_723__13 " + $d);
end

rule "bath_rule_723__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_723__14 " + $d);
end

rule "bath_rule_723__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_723__15 " + $d);
end

rule "bath_rule_723__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_723__16 " + $d);
end

rule "bath_rule_723__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_723__17 " + $d);
end

rule "bath_rule_723__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_723__18 " + $d);
end

rule "bath_rule_723__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_723__19 " + $d);
end

rule "bath_rule_723__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_723__20 " + $d);
end

rule "bath_rule_723__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_723__21 " + $d);
end

rule "bath_rule_723__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_723__22 " + $d);
end

rule "bath_rule_723__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_723__23 " + $d);
end

rule "bath_rule_723__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_723__24 " + $d);
end

rule "bath_rule_723__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_723__25 " + $d);
end

rule "bath_rule_723__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_723__26 " + $d);
end

rule "bath_rule_723__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_723__27 " + $d);
end

rule "bath_rule_723__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_723__28 " + $d);
end

rule "bath_rule_723__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_723__29 " + $d);
end

rule "bath_rule_723__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_723__30 " + $d);
end

rule "bath_rule_723__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_723__31 " + $d);
end

rule "bath_rule_723__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_723__32 " + $d);
end

rule "bath_rule_723__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_723__33 " + $d);
end

rule "bath_rule_723__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_723__34 " + $d);
end

rule "bath_rule_723__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_723__35 " + $d);
end

rule "bath_rule_723__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_723__36 " + $d);
end

rule "bath_rule_723__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_723__37 " + $d);
end

rule "bath_rule_723__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_723__38 " + $d);
end

rule "bath_rule_723__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_723__39 " + $d);
end

rule "bath_rule_723__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_723__40 " + $d);
end

rule "bath_rule_723__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_723__41 " + $d);
end

rule "bath_rule_723__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_723__42 " + $d);
end

rule "bath_rule_723__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_723__43 " + $d);
end

rule "bath_rule_723__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_723__44 " + $d);
end

rule "bath_rule_723__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_723__45 " + $d);
end

rule "bath_rule_723__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_723__46 " + $d);
end

rule "bath_rule_723__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_723__47 " + $d);
end

rule "bath_rule_723__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_723__48 " + $d);
end

rule "bath_rule_723__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_723__49 " + $d);
end

rule "bath_rule_723__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_723__50 " + $d);
end

rule "bath_rule_723__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_723__51 " + $d);
end

rule "bath_rule_723__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_723__52 " + $d);
end

rule "bath_rule_723__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_723__53 " + $d);
end

rule "bath_rule_723__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_723__54 " + $d);
end

rule "bath_rule_723__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_723__55 " + $d);
end

rule "bath_rule_723__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_723__56 " + $d);
end

rule "bath_rule_723__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_723__57 " + $d);
end

rule "bath_rule_723__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_723__58 " + $d);
end

rule "bath_rule_723__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_723__59 " + $d);
end

rule "bath_rule_723__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_723__60 " + $d);
end

rule "bath_rule_723__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_723__61 " + $d);
end

rule "bath_rule_723__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_723__62 " + $d);
end

rule "bath_rule_723__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_723__63 " + $d);
end

rule "bath_rule_723__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_723__64 " + $d);
end

rule "bath_rule_723__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_723__65 " + $d);
end

rule "bath_rule_723__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_723__66 " + $d);
end

rule "bath_rule_723__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_723__67 " + $d);
end

rule "bath_rule_723__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_723__68 " + $d);
end

rule "bath_rule_723__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_723__69 " + $d);
end

rule "bath_rule_723__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_723__70 " + $d);
end

rule "bath_rule_723__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_723__71 " + $d);
end

rule "bath_rule_723__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_723__72 " + $d);
end

rule "bath_rule_723__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_723__73 " + $d);
end

rule "bath_rule_723__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_723__74 " + $d);
end

rule "bath_rule_723__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_723__75 " + $d);
end

rule "bath_rule_723__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_723__76 " + $d);
end

rule "bath_rule_723__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_723__77 " + $d);
end

rule "bath_rule_723__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_723__78 " + $d);
end

rule "bath_rule_723__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_723__79 " + $d);
end

rule "bath_rule_723__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_723__80 " + $d);
end

rule "bath_rule_723__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_723__81 " + $d);
end

rule "bath_rule_723__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_723__82 " + $d);
end

rule "bath_rule_723__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_723__83 " + $d);
end

rule "bath_rule_723__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_723__84 " + $d);
end

rule "bath_rule_723__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_723__85 " + $d);
end

rule "bath_rule_723__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_723__86 " + $d);
end

rule "bath_rule_723__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_723__87 " + $d);
end

rule "bath_rule_723__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_723__88 " + $d);
end

rule "bath_rule_723__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_723__89 " + $d);
end

rule "bath_rule_723__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_723__90 " + $d);
end

rule "bath_rule_723__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_723__91 " + $d);
end

rule "bath_rule_723__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_723__92 " + $d);
end

rule "bath_rule_723__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_723__93 " + $d);
end

rule "bath_rule_723__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_723__94 " + $d);
end

rule "bath_rule_723__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_723__95 " + $d);
end

rule "bath_rule_723__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_723__96 " + $d);
end

rule "bath_rule_723__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_723__97 " + $d);
end

rule "bath_rule_723__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_723__98 " + $d);
end

rule "bath_rule_723__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_723__99 " + $d);
end

rule "bath_rule_723__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_723__100 " + $d);
end

