rule "bath_rule_892__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_892__0 " + $d);
end

rule "bath_rule_892__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_892__1 " + $d);
end

rule "bath_rule_892__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_892__2 " + $d);
end

rule "bath_rule_892__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_892__3 " + $d);
end

rule "bath_rule_892__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_892__4 " + $d);
end

rule "bath_rule_892__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_892__5 " + $d);
end

rule "bath_rule_892__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_892__6 " + $d);
end

rule "bath_rule_892__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_892__7 " + $d);
end

rule "bath_rule_892__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_892__8 " + $d);
end

rule "bath_rule_892__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_892__9 " + $d);
end

rule "bath_rule_892__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_892__10 " + $d);
end

rule "bath_rule_892__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_892__11 " + $d);
end

rule "bath_rule_892__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_892__12 " + $d);
end

rule "bath_rule_892__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_892__13 " + $d);
end

rule "bath_rule_892__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_892__14 " + $d);
end

rule "bath_rule_892__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_892__15 " + $d);
end

rule "bath_rule_892__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_892__16 " + $d);
end

rule "bath_rule_892__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_892__17 " + $d);
end

rule "bath_rule_892__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_892__18 " + $d);
end

rule "bath_rule_892__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_892__19 " + $d);
end

rule "bath_rule_892__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_892__20 " + $d);
end

rule "bath_rule_892__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_892__21 " + $d);
end

rule "bath_rule_892__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_892__22 " + $d);
end

rule "bath_rule_892__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_892__23 " + $d);
end

rule "bath_rule_892__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_892__24 " + $d);
end

rule "bath_rule_892__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_892__25 " + $d);
end

rule "bath_rule_892__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_892__26 " + $d);
end

rule "bath_rule_892__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_892__27 " + $d);
end

rule "bath_rule_892__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_892__28 " + $d);
end

rule "bath_rule_892__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_892__29 " + $d);
end

rule "bath_rule_892__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_892__30 " + $d);
end

rule "bath_rule_892__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_892__31 " + $d);
end

rule "bath_rule_892__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_892__32 " + $d);
end

rule "bath_rule_892__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_892__33 " + $d);
end

rule "bath_rule_892__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_892__34 " + $d);
end

rule "bath_rule_892__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_892__35 " + $d);
end

rule "bath_rule_892__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_892__36 " + $d);
end

rule "bath_rule_892__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_892__37 " + $d);
end

rule "bath_rule_892__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_892__38 " + $d);
end

rule "bath_rule_892__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_892__39 " + $d);
end

rule "bath_rule_892__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_892__40 " + $d);
end

rule "bath_rule_892__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_892__41 " + $d);
end

rule "bath_rule_892__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_892__42 " + $d);
end

rule "bath_rule_892__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_892__43 " + $d);
end

rule "bath_rule_892__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_892__44 " + $d);
end

rule "bath_rule_892__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_892__45 " + $d);
end

rule "bath_rule_892__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_892__46 " + $d);
end

rule "bath_rule_892__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_892__47 " + $d);
end

rule "bath_rule_892__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_892__48 " + $d);
end

rule "bath_rule_892__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_892__49 " + $d);
end

rule "bath_rule_892__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_892__50 " + $d);
end

rule "bath_rule_892__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_892__51 " + $d);
end

rule "bath_rule_892__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_892__52 " + $d);
end

rule "bath_rule_892__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_892__53 " + $d);
end

rule "bath_rule_892__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_892__54 " + $d);
end

rule "bath_rule_892__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_892__55 " + $d);
end

rule "bath_rule_892__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_892__56 " + $d);
end

rule "bath_rule_892__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_892__57 " + $d);
end

rule "bath_rule_892__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_892__58 " + $d);
end

rule "bath_rule_892__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_892__59 " + $d);
end

rule "bath_rule_892__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_892__60 " + $d);
end

rule "bath_rule_892__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_892__61 " + $d);
end

rule "bath_rule_892__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_892__62 " + $d);
end

rule "bath_rule_892__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_892__63 " + $d);
end

rule "bath_rule_892__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_892__64 " + $d);
end

rule "bath_rule_892__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_892__65 " + $d);
end

rule "bath_rule_892__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_892__66 " + $d);
end

rule "bath_rule_892__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_892__67 " + $d);
end

rule "bath_rule_892__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_892__68 " + $d);
end

rule "bath_rule_892__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_892__69 " + $d);
end

rule "bath_rule_892__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_892__70 " + $d);
end

rule "bath_rule_892__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_892__71 " + $d);
end

rule "bath_rule_892__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_892__72 " + $d);
end

rule "bath_rule_892__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_892__73 " + $d);
end

rule "bath_rule_892__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_892__74 " + $d);
end

rule "bath_rule_892__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_892__75 " + $d);
end

rule "bath_rule_892__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_892__76 " + $d);
end

rule "bath_rule_892__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_892__77 " + $d);
end

rule "bath_rule_892__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_892__78 " + $d);
end

rule "bath_rule_892__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_892__79 " + $d);
end

rule "bath_rule_892__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_892__80 " + $d);
end

rule "bath_rule_892__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_892__81 " + $d);
end

rule "bath_rule_892__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_892__82 " + $d);
end

rule "bath_rule_892__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_892__83 " + $d);
end

rule "bath_rule_892__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_892__84 " + $d);
end

rule "bath_rule_892__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_892__85 " + $d);
end

rule "bath_rule_892__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_892__86 " + $d);
end

rule "bath_rule_892__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_892__87 " + $d);
end

rule "bath_rule_892__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_892__88 " + $d);
end

rule "bath_rule_892__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_892__89 " + $d);
end

rule "bath_rule_892__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_892__90 " + $d);
end

rule "bath_rule_892__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_892__91 " + $d);
end

rule "bath_rule_892__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_892__92 " + $d);
end

rule "bath_rule_892__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_892__93 " + $d);
end

rule "bath_rule_892__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_892__94 " + $d);
end

rule "bath_rule_892__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_892__95 " + $d);
end

rule "bath_rule_892__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_892__96 " + $d);
end

rule "bath_rule_892__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_892__97 " + $d);
end

rule "bath_rule_892__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_892__98 " + $d);
end

rule "bath_rule_892__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_892__99 " + $d);
end

rule "bath_rule_892__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_892__100 " + $d);
end

