rule "bath_rule_870__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_870__0 " + $d);
end

rule "bath_rule_870__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_870__1 " + $d);
end

rule "bath_rule_870__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_870__2 " + $d);
end

rule "bath_rule_870__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_870__3 " + $d);
end

rule "bath_rule_870__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_870__4 " + $d);
end

rule "bath_rule_870__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_870__5 " + $d);
end

rule "bath_rule_870__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_870__6 " + $d);
end

rule "bath_rule_870__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_870__7 " + $d);
end

rule "bath_rule_870__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_870__8 " + $d);
end

rule "bath_rule_870__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_870__9 " + $d);
end

rule "bath_rule_870__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_870__10 " + $d);
end

rule "bath_rule_870__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_870__11 " + $d);
end

rule "bath_rule_870__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_870__12 " + $d);
end

rule "bath_rule_870__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_870__13 " + $d);
end

rule "bath_rule_870__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_870__14 " + $d);
end

rule "bath_rule_870__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_870__15 " + $d);
end

rule "bath_rule_870__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_870__16 " + $d);
end

rule "bath_rule_870__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_870__17 " + $d);
end

rule "bath_rule_870__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_870__18 " + $d);
end

rule "bath_rule_870__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_870__19 " + $d);
end

rule "bath_rule_870__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_870__20 " + $d);
end

rule "bath_rule_870__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_870__21 " + $d);
end

rule "bath_rule_870__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_870__22 " + $d);
end

rule "bath_rule_870__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_870__23 " + $d);
end

rule "bath_rule_870__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_870__24 " + $d);
end

rule "bath_rule_870__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_870__25 " + $d);
end

rule "bath_rule_870__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_870__26 " + $d);
end

rule "bath_rule_870__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_870__27 " + $d);
end

rule "bath_rule_870__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_870__28 " + $d);
end

rule "bath_rule_870__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_870__29 " + $d);
end

rule "bath_rule_870__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_870__30 " + $d);
end

rule "bath_rule_870__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_870__31 " + $d);
end

rule "bath_rule_870__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_870__32 " + $d);
end

rule "bath_rule_870__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_870__33 " + $d);
end

rule "bath_rule_870__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_870__34 " + $d);
end

rule "bath_rule_870__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_870__35 " + $d);
end

rule "bath_rule_870__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_870__36 " + $d);
end

rule "bath_rule_870__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_870__37 " + $d);
end

rule "bath_rule_870__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_870__38 " + $d);
end

rule "bath_rule_870__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_870__39 " + $d);
end

rule "bath_rule_870__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_870__40 " + $d);
end

rule "bath_rule_870__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_870__41 " + $d);
end

rule "bath_rule_870__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_870__42 " + $d);
end

rule "bath_rule_870__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_870__43 " + $d);
end

rule "bath_rule_870__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_870__44 " + $d);
end

rule "bath_rule_870__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_870__45 " + $d);
end

rule "bath_rule_870__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_870__46 " + $d);
end

rule "bath_rule_870__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_870__47 " + $d);
end

rule "bath_rule_870__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_870__48 " + $d);
end

rule "bath_rule_870__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_870__49 " + $d);
end

rule "bath_rule_870__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_870__50 " + $d);
end

rule "bath_rule_870__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_870__51 " + $d);
end

rule "bath_rule_870__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_870__52 " + $d);
end

rule "bath_rule_870__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_870__53 " + $d);
end

rule "bath_rule_870__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_870__54 " + $d);
end

rule "bath_rule_870__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_870__55 " + $d);
end

rule "bath_rule_870__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_870__56 " + $d);
end

rule "bath_rule_870__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_870__57 " + $d);
end

rule "bath_rule_870__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_870__58 " + $d);
end

rule "bath_rule_870__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_870__59 " + $d);
end

rule "bath_rule_870__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_870__60 " + $d);
end

rule "bath_rule_870__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_870__61 " + $d);
end

rule "bath_rule_870__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_870__62 " + $d);
end

rule "bath_rule_870__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_870__63 " + $d);
end

rule "bath_rule_870__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_870__64 " + $d);
end

rule "bath_rule_870__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_870__65 " + $d);
end

rule "bath_rule_870__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_870__66 " + $d);
end

rule "bath_rule_870__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_870__67 " + $d);
end

rule "bath_rule_870__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_870__68 " + $d);
end

rule "bath_rule_870__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_870__69 " + $d);
end

rule "bath_rule_870__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_870__70 " + $d);
end

rule "bath_rule_870__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_870__71 " + $d);
end

rule "bath_rule_870__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_870__72 " + $d);
end

rule "bath_rule_870__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_870__73 " + $d);
end

rule "bath_rule_870__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_870__74 " + $d);
end

rule "bath_rule_870__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_870__75 " + $d);
end

rule "bath_rule_870__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_870__76 " + $d);
end

rule "bath_rule_870__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_870__77 " + $d);
end

rule "bath_rule_870__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_870__78 " + $d);
end

rule "bath_rule_870__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_870__79 " + $d);
end

rule "bath_rule_870__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_870__80 " + $d);
end

rule "bath_rule_870__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_870__81 " + $d);
end

rule "bath_rule_870__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_870__82 " + $d);
end

rule "bath_rule_870__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_870__83 " + $d);
end

rule "bath_rule_870__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_870__84 " + $d);
end

rule "bath_rule_870__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_870__85 " + $d);
end

rule "bath_rule_870__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_870__86 " + $d);
end

rule "bath_rule_870__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_870__87 " + $d);
end

rule "bath_rule_870__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_870__88 " + $d);
end

rule "bath_rule_870__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_870__89 " + $d);
end

rule "bath_rule_870__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_870__90 " + $d);
end

rule "bath_rule_870__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_870__91 " + $d);
end

rule "bath_rule_870__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_870__92 " + $d);
end

rule "bath_rule_870__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_870__93 " + $d);
end

rule "bath_rule_870__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_870__94 " + $d);
end

rule "bath_rule_870__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_870__95 " + $d);
end

rule "bath_rule_870__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_870__96 " + $d);
end

rule "bath_rule_870__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_870__97 " + $d);
end

rule "bath_rule_870__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_870__98 " + $d);
end

rule "bath_rule_870__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_870__99 " + $d);
end

rule "bath_rule_870__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_870__100 " + $d);
end

