rule "bath_rule_998__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_998__0 " + $d);
end

rule "bath_rule_998__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_998__1 " + $d);
end

rule "bath_rule_998__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_998__2 " + $d);
end

rule "bath_rule_998__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_998__3 " + $d);
end

rule "bath_rule_998__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_998__4 " + $d);
end

rule "bath_rule_998__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_998__5 " + $d);
end

rule "bath_rule_998__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_998__6 " + $d);
end

rule "bath_rule_998__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_998__7 " + $d);
end

rule "bath_rule_998__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_998__8 " + $d);
end

rule "bath_rule_998__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_998__9 " + $d);
end

rule "bath_rule_998__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_998__10 " + $d);
end

rule "bath_rule_998__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_998__11 " + $d);
end

rule "bath_rule_998__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_998__12 " + $d);
end

rule "bath_rule_998__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_998__13 " + $d);
end

rule "bath_rule_998__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_998__14 " + $d);
end

rule "bath_rule_998__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_998__15 " + $d);
end

rule "bath_rule_998__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_998__16 " + $d);
end

rule "bath_rule_998__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_998__17 " + $d);
end

rule "bath_rule_998__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_998__18 " + $d);
end

rule "bath_rule_998__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_998__19 " + $d);
end

rule "bath_rule_998__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_998__20 " + $d);
end

rule "bath_rule_998__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_998__21 " + $d);
end

rule "bath_rule_998__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_998__22 " + $d);
end

rule "bath_rule_998__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_998__23 " + $d);
end

rule "bath_rule_998__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_998__24 " + $d);
end

rule "bath_rule_998__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_998__25 " + $d);
end

rule "bath_rule_998__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_998__26 " + $d);
end

rule "bath_rule_998__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_998__27 " + $d);
end

rule "bath_rule_998__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_998__28 " + $d);
end

rule "bath_rule_998__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_998__29 " + $d);
end

rule "bath_rule_998__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_998__30 " + $d);
end

rule "bath_rule_998__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_998__31 " + $d);
end

rule "bath_rule_998__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_998__32 " + $d);
end

rule "bath_rule_998__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_998__33 " + $d);
end

rule "bath_rule_998__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_998__34 " + $d);
end

rule "bath_rule_998__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_998__35 " + $d);
end

rule "bath_rule_998__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_998__36 " + $d);
end

rule "bath_rule_998__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_998__37 " + $d);
end

rule "bath_rule_998__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_998__38 " + $d);
end

rule "bath_rule_998__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_998__39 " + $d);
end

rule "bath_rule_998__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_998__40 " + $d);
end

rule "bath_rule_998__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_998__41 " + $d);
end

rule "bath_rule_998__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_998__42 " + $d);
end

rule "bath_rule_998__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_998__43 " + $d);
end

rule "bath_rule_998__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_998__44 " + $d);
end

rule "bath_rule_998__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_998__45 " + $d);
end

rule "bath_rule_998__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_998__46 " + $d);
end

rule "bath_rule_998__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_998__47 " + $d);
end

rule "bath_rule_998__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_998__48 " + $d);
end

rule "bath_rule_998__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_998__49 " + $d);
end

rule "bath_rule_998__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_998__50 " + $d);
end

rule "bath_rule_998__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_998__51 " + $d);
end

rule "bath_rule_998__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_998__52 " + $d);
end

rule "bath_rule_998__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_998__53 " + $d);
end

rule "bath_rule_998__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_998__54 " + $d);
end

rule "bath_rule_998__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_998__55 " + $d);
end

rule "bath_rule_998__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_998__56 " + $d);
end

rule "bath_rule_998__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_998__57 " + $d);
end

rule "bath_rule_998__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_998__58 " + $d);
end

rule "bath_rule_998__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_998__59 " + $d);
end

rule "bath_rule_998__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_998__60 " + $d);
end

rule "bath_rule_998__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_998__61 " + $d);
end

rule "bath_rule_998__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_998__62 " + $d);
end

rule "bath_rule_998__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_998__63 " + $d);
end

rule "bath_rule_998__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_998__64 " + $d);
end

rule "bath_rule_998__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_998__65 " + $d);
end

rule "bath_rule_998__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_998__66 " + $d);
end

rule "bath_rule_998__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_998__67 " + $d);
end

rule "bath_rule_998__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_998__68 " + $d);
end

rule "bath_rule_998__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_998__69 " + $d);
end

rule "bath_rule_998__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_998__70 " + $d);
end

rule "bath_rule_998__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_998__71 " + $d);
end

rule "bath_rule_998__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_998__72 " + $d);
end

rule "bath_rule_998__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_998__73 " + $d);
end

rule "bath_rule_998__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_998__74 " + $d);
end

rule "bath_rule_998__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_998__75 " + $d);
end

rule "bath_rule_998__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_998__76 " + $d);
end

rule "bath_rule_998__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_998__77 " + $d);
end

rule "bath_rule_998__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_998__78 " + $d);
end

rule "bath_rule_998__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_998__79 " + $d);
end

rule "bath_rule_998__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_998__80 " + $d);
end

rule "bath_rule_998__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_998__81 " + $d);
end

rule "bath_rule_998__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_998__82 " + $d);
end

rule "bath_rule_998__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_998__83 " + $d);
end

rule "bath_rule_998__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_998__84 " + $d);
end

rule "bath_rule_998__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_998__85 " + $d);
end

rule "bath_rule_998__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_998__86 " + $d);
end

rule "bath_rule_998__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_998__87 " + $d);
end

rule "bath_rule_998__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_998__88 " + $d);
end

rule "bath_rule_998__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_998__89 " + $d);
end

rule "bath_rule_998__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_998__90 " + $d);
end

rule "bath_rule_998__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_998__91 " + $d);
end

rule "bath_rule_998__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_998__92 " + $d);
end

rule "bath_rule_998__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_998__93 " + $d);
end

rule "bath_rule_998__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_998__94 " + $d);
end

rule "bath_rule_998__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_998__95 " + $d);
end

rule "bath_rule_998__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_998__96 " + $d);
end

rule "bath_rule_998__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_998__97 " + $d);
end

rule "bath_rule_998__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_998__98 " + $d);
end

rule "bath_rule_998__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_998__99 " + $d);
end

rule "bath_rule_998__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_998__100 " + $d);
end

