rule "bath_rule_948__0"
    when
        $d :Double(this == 0)
    then
        System.err.println("bath_rule_948__0 " + $d);
end

rule "bath_rule_948__1"
    when
        $d :Double(this == 1)
    then
        System.err.println("bath_rule_948__1 " + $d);
end

rule "bath_rule_948__2"
    when
        $d :Double(this == 2)
    then
        System.err.println("bath_rule_948__2 " + $d);
end

rule "bath_rule_948__3"
    when
        $d :Double(this == 3)
    then
        System.err.println("bath_rule_948__3 " + $d);
end

rule "bath_rule_948__4"
    when
        $d :Double(this == 4)
    then
        System.err.println("bath_rule_948__4 " + $d);
end

rule "bath_rule_948__5"
    when
        $d :Double(this == 5)
    then
        System.err.println("bath_rule_948__5 " + $d);
end

rule "bath_rule_948__6"
    when
        $d :Double(this == 6)
    then
        System.err.println("bath_rule_948__6 " + $d);
end

rule "bath_rule_948__7"
    when
        $d :Double(this == 7)
    then
        System.err.println("bath_rule_948__7 " + $d);
end

rule "bath_rule_948__8"
    when
        $d :Double(this == 8)
    then
        System.err.println("bath_rule_948__8 " + $d);
end

rule "bath_rule_948__9"
    when
        $d :Double(this == 9)
    then
        System.err.println("bath_rule_948__9 " + $d);
end

rule "bath_rule_948__10"
    when
        $d :Double(this == 10)
    then
        System.err.println("bath_rule_948__10 " + $d);
end

rule "bath_rule_948__11"
    when
        $d :Double(this == 11)
    then
        System.err.println("bath_rule_948__11 " + $d);
end

rule "bath_rule_948__12"
    when
        $d :Double(this == 12)
    then
        System.err.println("bath_rule_948__12 " + $d);
end

rule "bath_rule_948__13"
    when
        $d :Double(this == 13)
    then
        System.err.println("bath_rule_948__13 " + $d);
end

rule "bath_rule_948__14"
    when
        $d :Double(this == 14)
    then
        System.err.println("bath_rule_948__14 " + $d);
end

rule "bath_rule_948__15"
    when
        $d :Double(this == 15)
    then
        System.err.println("bath_rule_948__15 " + $d);
end

rule "bath_rule_948__16"
    when
        $d :Double(this == 16)
    then
        System.err.println("bath_rule_948__16 " + $d);
end

rule "bath_rule_948__17"
    when
        $d :Double(this == 17)
    then
        System.err.println("bath_rule_948__17 " + $d);
end

rule "bath_rule_948__18"
    when
        $d :Double(this == 18)
    then
        System.err.println("bath_rule_948__18 " + $d);
end

rule "bath_rule_948__19"
    when
        $d :Double(this == 19)
    then
        System.err.println("bath_rule_948__19 " + $d);
end

rule "bath_rule_948__20"
    when
        $d :Double(this == 20)
    then
        System.err.println("bath_rule_948__20 " + $d);
end

rule "bath_rule_948__21"
    when
        $d :Double(this == 21)
    then
        System.err.println("bath_rule_948__21 " + $d);
end

rule "bath_rule_948__22"
    when
        $d :Double(this == 22)
    then
        System.err.println("bath_rule_948__22 " + $d);
end

rule "bath_rule_948__23"
    when
        $d :Double(this == 23)
    then
        System.err.println("bath_rule_948__23 " + $d);
end

rule "bath_rule_948__24"
    when
        $d :Double(this == 24)
    then
        System.err.println("bath_rule_948__24 " + $d);
end

rule "bath_rule_948__25"
    when
        $d :Double(this == 25)
    then
        System.err.println("bath_rule_948__25 " + $d);
end

rule "bath_rule_948__26"
    when
        $d :Double(this == 26)
    then
        System.err.println("bath_rule_948__26 " + $d);
end

rule "bath_rule_948__27"
    when
        $d :Double(this == 27)
    then
        System.err.println("bath_rule_948__27 " + $d);
end

rule "bath_rule_948__28"
    when
        $d :Double(this == 28)
    then
        System.err.println("bath_rule_948__28 " + $d);
end

rule "bath_rule_948__29"
    when
        $d :Double(this == 29)
    then
        System.err.println("bath_rule_948__29 " + $d);
end

rule "bath_rule_948__30"
    when
        $d :Double(this == 30)
    then
        System.err.println("bath_rule_948__30 " + $d);
end

rule "bath_rule_948__31"
    when
        $d :Double(this == 31)
    then
        System.err.println("bath_rule_948__31 " + $d);
end

rule "bath_rule_948__32"
    when
        $d :Double(this == 32)
    then
        System.err.println("bath_rule_948__32 " + $d);
end

rule "bath_rule_948__33"
    when
        $d :Double(this == 33)
    then
        System.err.println("bath_rule_948__33 " + $d);
end

rule "bath_rule_948__34"
    when
        $d :Double(this == 34)
    then
        System.err.println("bath_rule_948__34 " + $d);
end

rule "bath_rule_948__35"
    when
        $d :Double(this == 35)
    then
        System.err.println("bath_rule_948__35 " + $d);
end

rule "bath_rule_948__36"
    when
        $d :Double(this == 36)
    then
        System.err.println("bath_rule_948__36 " + $d);
end

rule "bath_rule_948__37"
    when
        $d :Double(this == 37)
    then
        System.err.println("bath_rule_948__37 " + $d);
end

rule "bath_rule_948__38"
    when
        $d :Double(this == 38)
    then
        System.err.println("bath_rule_948__38 " + $d);
end

rule "bath_rule_948__39"
    when
        $d :Double(this == 39)
    then
        System.err.println("bath_rule_948__39 " + $d);
end

rule "bath_rule_948__40"
    when
        $d :Double(this == 40)
    then
        System.err.println("bath_rule_948__40 " + $d);
end

rule "bath_rule_948__41"
    when
        $d :Double(this == 41)
    then
        System.err.println("bath_rule_948__41 " + $d);
end

rule "bath_rule_948__42"
    when
        $d :Double(this == 42)
    then
        System.err.println("bath_rule_948__42 " + $d);
end

rule "bath_rule_948__43"
    when
        $d :Double(this == 43)
    then
        System.err.println("bath_rule_948__43 " + $d);
end

rule "bath_rule_948__44"
    when
        $d :Double(this == 44)
    then
        System.err.println("bath_rule_948__44 " + $d);
end

rule "bath_rule_948__45"
    when
        $d :Double(this == 45)
    then
        System.err.println("bath_rule_948__45 " + $d);
end

rule "bath_rule_948__46"
    when
        $d :Double(this == 46)
    then
        System.err.println("bath_rule_948__46 " + $d);
end

rule "bath_rule_948__47"
    when
        $d :Double(this == 47)
    then
        System.err.println("bath_rule_948__47 " + $d);
end

rule "bath_rule_948__48"
    when
        $d :Double(this == 48)
    then
        System.err.println("bath_rule_948__48 " + $d);
end

rule "bath_rule_948__49"
    when
        $d :Double(this == 49)
    then
        System.err.println("bath_rule_948__49 " + $d);
end

rule "bath_rule_948__50"
    when
        $d :Double(this == 50)
    then
        System.err.println("bath_rule_948__50 " + $d);
end

rule "bath_rule_948__51"
    when
        $d :Double(this == 51)
    then
        System.err.println("bath_rule_948__51 " + $d);
end

rule "bath_rule_948__52"
    when
        $d :Double(this == 52)
    then
        System.err.println("bath_rule_948__52 " + $d);
end

rule "bath_rule_948__53"
    when
        $d :Double(this == 53)
    then
        System.err.println("bath_rule_948__53 " + $d);
end

rule "bath_rule_948__54"
    when
        $d :Double(this == 54)
    then
        System.err.println("bath_rule_948__54 " + $d);
end

rule "bath_rule_948__55"
    when
        $d :Double(this == 55)
    then
        System.err.println("bath_rule_948__55 " + $d);
end

rule "bath_rule_948__56"
    when
        $d :Double(this == 56)
    then
        System.err.println("bath_rule_948__56 " + $d);
end

rule "bath_rule_948__57"
    when
        $d :Double(this == 57)
    then
        System.err.println("bath_rule_948__57 " + $d);
end

rule "bath_rule_948__58"
    when
        $d :Double(this == 58)
    then
        System.err.println("bath_rule_948__58 " + $d);
end

rule "bath_rule_948__59"
    when
        $d :Double(this == 59)
    then
        System.err.println("bath_rule_948__59 " + $d);
end

rule "bath_rule_948__60"
    when
        $d :Double(this == 60)
    then
        System.err.println("bath_rule_948__60 " + $d);
end

rule "bath_rule_948__61"
    when
        $d :Double(this == 61)
    then
        System.err.println("bath_rule_948__61 " + $d);
end

rule "bath_rule_948__62"
    when
        $d :Double(this == 62)
    then
        System.err.println("bath_rule_948__62 " + $d);
end

rule "bath_rule_948__63"
    when
        $d :Double(this == 63)
    then
        System.err.println("bath_rule_948__63 " + $d);
end

rule "bath_rule_948__64"
    when
        $d :Double(this == 64)
    then
        System.err.println("bath_rule_948__64 " + $d);
end

rule "bath_rule_948__65"
    when
        $d :Double(this == 65)
    then
        System.err.println("bath_rule_948__65 " + $d);
end

rule "bath_rule_948__66"
    when
        $d :Double(this == 66)
    then
        System.err.println("bath_rule_948__66 " + $d);
end

rule "bath_rule_948__67"
    when
        $d :Double(this == 67)
    then
        System.err.println("bath_rule_948__67 " + $d);
end

rule "bath_rule_948__68"
    when
        $d :Double(this == 68)
    then
        System.err.println("bath_rule_948__68 " + $d);
end

rule "bath_rule_948__69"
    when
        $d :Double(this == 69)
    then
        System.err.println("bath_rule_948__69 " + $d);
end

rule "bath_rule_948__70"
    when
        $d :Double(this == 70)
    then
        System.err.println("bath_rule_948__70 " + $d);
end

rule "bath_rule_948__71"
    when
        $d :Double(this == 71)
    then
        System.err.println("bath_rule_948__71 " + $d);
end

rule "bath_rule_948__72"
    when
        $d :Double(this == 72)
    then
        System.err.println("bath_rule_948__72 " + $d);
end

rule "bath_rule_948__73"
    when
        $d :Double(this == 73)
    then
        System.err.println("bath_rule_948__73 " + $d);
end

rule "bath_rule_948__74"
    when
        $d :Double(this == 74)
    then
        System.err.println("bath_rule_948__74 " + $d);
end

rule "bath_rule_948__75"
    when
        $d :Double(this == 75)
    then
        System.err.println("bath_rule_948__75 " + $d);
end

rule "bath_rule_948__76"
    when
        $d :Double(this == 76)
    then
        System.err.println("bath_rule_948__76 " + $d);
end

rule "bath_rule_948__77"
    when
        $d :Double(this == 77)
    then
        System.err.println("bath_rule_948__77 " + $d);
end

rule "bath_rule_948__78"
    when
        $d :Double(this == 78)
    then
        System.err.println("bath_rule_948__78 " + $d);
end

rule "bath_rule_948__79"
    when
        $d :Double(this == 79)
    then
        System.err.println("bath_rule_948__79 " + $d);
end

rule "bath_rule_948__80"
    when
        $d :Double(this == 80)
    then
        System.err.println("bath_rule_948__80 " + $d);
end

rule "bath_rule_948__81"
    when
        $d :Double(this == 81)
    then
        System.err.println("bath_rule_948__81 " + $d);
end

rule "bath_rule_948__82"
    when
        $d :Double(this == 82)
    then
        System.err.println("bath_rule_948__82 " + $d);
end

rule "bath_rule_948__83"
    when
        $d :Double(this == 83)
    then
        System.err.println("bath_rule_948__83 " + $d);
end

rule "bath_rule_948__84"
    when
        $d :Double(this == 84)
    then
        System.err.println("bath_rule_948__84 " + $d);
end

rule "bath_rule_948__85"
    when
        $d :Double(this == 85)
    then
        System.err.println("bath_rule_948__85 " + $d);
end

rule "bath_rule_948__86"
    when
        $d :Double(this == 86)
    then
        System.err.println("bath_rule_948__86 " + $d);
end

rule "bath_rule_948__87"
    when
        $d :Double(this == 87)
    then
        System.err.println("bath_rule_948__87 " + $d);
end

rule "bath_rule_948__88"
    when
        $d :Double(this == 88)
    then
        System.err.println("bath_rule_948__88 " + $d);
end

rule "bath_rule_948__89"
    when
        $d :Double(this == 89)
    then
        System.err.println("bath_rule_948__89 " + $d);
end

rule "bath_rule_948__90"
    when
        $d :Double(this == 90)
    then
        System.err.println("bath_rule_948__90 " + $d);
end

rule "bath_rule_948__91"
    when
        $d :Double(this == 91)
    then
        System.err.println("bath_rule_948__91 " + $d);
end

rule "bath_rule_948__92"
    when
        $d :Double(this == 92)
    then
        System.err.println("bath_rule_948__92 " + $d);
end

rule "bath_rule_948__93"
    when
        $d :Double(this == 93)
    then
        System.err.println("bath_rule_948__93 " + $d);
end

rule "bath_rule_948__94"
    when
        $d :Double(this == 94)
    then
        System.err.println("bath_rule_948__94 " + $d);
end

rule "bath_rule_948__95"
    when
        $d :Double(this == 95)
    then
        System.err.println("bath_rule_948__95 " + $d);
end

rule "bath_rule_948__96"
    when
        $d :Double(this == 96)
    then
        System.err.println("bath_rule_948__96 " + $d);
end

rule "bath_rule_948__97"
    when
        $d :Double(this == 97)
    then
        System.err.println("bath_rule_948__97 " + $d);
end

rule "bath_rule_948__98"
    when
        $d :Double(this == 98)
    then
        System.err.println("bath_rule_948__98 " + $d);
end

rule "bath_rule_948__99"
    when
        $d :Double(this == 99)
    then
        System.err.println("bath_rule_948__99 " + $d);
end

rule "bath_rule_948__100"
    when
        $d :Double(this == 100)
    then
        System.err.println("bath_rule_948__100 " + $d);
end

